import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import type {Dataset} from '../src/contracts.ts';import {initialScenario,fighter,statsFor} from '../src/model.ts';import {fullBuild} from '../src/fullBuild.ts';import {calculateOptimalBuild,evaluateBuild,exclusiveGroupsValid,normalizeMetric} from '../src/buildEvaluation.ts';import {contextualRecommendation,analyzeComposition,applyCounter} from '../src/contextRecommendations.ts';
const data:Dataset=JSON.parse(readFileSync(new URL('../public/data/pt_BR.json',import.meta.url),'utf8'));
test('min-max scales are bounded and a constant axis is neutral',()=>{assert.equal(normalizeMetric(200,100,300),.5);assert.equal(normalizeMetric(20,10,10),0);assert.equal(normalizeMetric(999,100,300),1);assert.equal(normalizeMetric(0,100,300),0);});
test('exclusive armor penetration, Lifeline and magic penetration groups cannot coexist',()=>{assert.equal(exclusiveGroupsValid(['3036','3033']),false);assert.equal(exclusiveGroupsValid(['3036','3071']),false);assert.equal(exclusiveGroupsValid(['3156','6673']),false);assert.equal(exclusiveGroupsValid(['3135','3137']),false);assert.equal(exclusiveGroupsValid(['3036','3031','3072']),true);});
test('normalized exact search matches independent exhaustive scoring and preserves tied incumbent',()=>{const s=initialScenario(data);s.weights={offense:50,defense:50,utility:0};const candidates=[['3031'],['2502'],['3072']];const rows=candidates.map(items=>evaluateBuild(items,s,data));const ds=rows.map(m=>m.dps),hs=rows.map(m=>m.ehp);const scores=rows.map(m=>.5*normalizeMetric(m.dps,Math.min(...ds),Math.max(...ds))+.5*normalizeMetric(m.ehp,Math.min(...hs),Math.max(...hs)));const r=calculateOptimalBuild(candidates,s,data);assert.equal(r.score,Math.max(...scores));assert.equal(r.count,3);const tie=calculateOptimalBuild([['3031'],['3031']],s,data,['3031']);assert.deepEqual(tie.items,['3031']);});
test('official Infinity Edge crit damage affects DPS, while AS overrides are capped',()=>{const s=initialScenario(data);const st=statsFor({...s.player,items:['3031']},data);assert.equal(st.critMultiplier,2.05);s.player.overrides={as:2.5};const a=evaluateBuild(['3031'],s,data);s.player.overrides={as:99};assert.equal(evaluateBuild(['3031'],s,data).dps,a.dps);s.enemy.overrides={armor:500};assert.ok(evaluateBuild(['3031'],s,data).dps<a.dps);});
test('matchup and draft presets do not depend on slider, use official compatible IDs, and stay separate until applied',()=>{const s=initialScenario(data);s.enemy=fighter(data,'Malphite');const before=JSON.stringify(s),a=contextualRecommendation(s,data,'Jinx',['Malphite'],'Matchup');assert.equal(JSON.stringify(s),before);s.weights={offense:0,defense:100,utility:0};const b=contextualRecommendation(s,data,'Jinx',['Malphite'],'Matchup');assert.deepEqual(a.preset,b.preset);assert.equal(a.items.length,2);assert.ok(a.items.includes('3036'));assert.ok(a.warnings.some(w=>w.includes('arremessos')));assert.ok(a.runes.every(id=>id!==9105||data.runes.some(t=>t.slots.some(row=>row.runes.some(r=>r.id===id)))));const next=applyCounter(s,data,a.preset);assert.deepEqual(next.weights,s.weights);assert.deepEqual(next.player.actions,s.player.actions);assert.deepEqual(next.player.owned,s.player.owned);assert.equal(fullBuild(next,data).target.length,6);assert.deepEqual(next.counterPreset,a.preset);assert.equal(next.player.locked.length,s.player.locked.length);});
test('draft composition is an explicit profile estimate; active champion alone determines counters',()=>{const enemies=['Darius','Zed','Talon','Jinx','Soraka'],s=initialScenario(data),t=analyzeComposition(enemies,data);assert.equal(t.count,5);assert.equal(t.physical,.8);assert.equal(t.magic,.2);const adc=contextualRecommendation(s,data,'Jinx',enemies,'Draft'),mage=contextualRecommendation(s,data,'Ahri',enemies,'Draft');assert.notDeepEqual(adc.items,mage.items);assert.equal(mage.preset.champion,'Ahri');assert.equal(s.player.champion,'Jinx');assert.equal(mage.preset.runes.selected.length,6);assert.equal(mage.preset.runes.shards.length,3);});
test('full target keeps gold informative, a compatible ADC affinity core, and no group conflicts',()=>{const s=initialScenario(data);s.weights={offense:0,defense:100,utility:0};s.budget=0;const a=fullBuild(s,data);s.budget=99999;assert.deepEqual(fullBuild(s,data).target,a.target);assert.equal(a.target.length,6);assert.ok(exclusiveGroupsValid(a.target));assert.ok(a.target.filter(id=>(data.items[id].stats.FlatPhysicalDamageMod??0)>0||(data.items[id].stats.FlatCritChanceMod??0)>0).length>=1);assert.ok(!a.target.includes('3087'));assert.equal(data.items['3087'].stats.FlatMagicDamageMod,45);});
