import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import type {Dataset} from '../src/contracts.ts';import {initialScenario,fighter,isBoot,statsFor} from '../src/model.ts';import {fullBuild,sequentialPurchases} from '../src/fullBuild.ts';import {SHARD_ROWS} from '../src/shards.ts';
const data:Dataset=JSON.parse(readFileSync(new URL('../public/data/pt_BR.json',import.meta.url),'utf8'));
test('six targets independent of budget and old slot count, with complete rune page',()=>{for(const champion of ['Shen','Ahri','Cassiopeia','Lulu','Leona','MasterYi','Zed']){const s=initialScenario(data);s.player=fighter(data,champion);s.budget=0;s.slots=0;const r=fullBuild(s,data);assert.equal(r.target.length,6,champion);assert.equal(new Set(r.target).size,6);assert.equal(r.target.filter(id=>isBoot(id,data)).length,champion==='Cassiopeia'?0:1);assert.equal(r.runes.selected.length,6);assert.equal(r.runes.shards.length,3);r.runes.shards.forEach((id,n)=>assert.ok(SHARD_ROWS[n].includes(id)));s.budget=6000;assert.deepEqual(fullBuild(s,data).target,r.target);}});
test('manual no boots; extremes change whole target and ties keep order',()=>{const s=initialScenario(data);s.player=fighter(data,'Ahri');s.player.boots='none';s.weights={offense:100,defense:0,utility:0};const a=fullBuild(s,data);assert.equal(a.target.filter(id=>isBoot(id,data)).length,0);s.weights={offense:0,defense:100,utility:0};const b=fullBuild(s,data,'balanced',a.target);assert.notDeepEqual(a.target,b.target);assert.deepEqual(fullBuild(s,data,'balanced',b.target).target,b.target);});
test('strict prefix does not skip expensive first item',()=>{const s=initialScenario(data);s.budget=1000;const p=sequentialPurchases(['3084','3158','1028'],s,data);assert.deepEqual(p.steps.map(x=>x.available),[false,false,false]);assert.equal(p.remaining,1000);});
test('T1 recipe credit allocated once; inventory unchanged; unlocked owned boot upgraded',()=>{const s=initialScenario(data);s.player.owned=['1001'];s.player.items=['1001'];s.player.locked=[];s.budget=6000;const before=JSON.stringify(s);const r=fullBuild(s,data);assert.ok(!r.target.includes('1001'));assert.equal(r.target.filter(id=>isBoot(id,data)).length,1);const p=sequentialPurchases(r.target,s,data);assert.equal(p.steps.reduce((n,x)=>n+x.credit,0),data.items['1001'].gold.total);assert.equal(JSON.stringify(s),before);});
test('owned final lock preserved and unlocked owned components credited in compatible upgrade',()=>{const s=initialScenario(data);s.player=fighter(data,'Ahri');s.player.owned=['3157','1052'];s.player.locked=['3157'];s.player.items=[...s.player.owned];const r=fullBuild(s,data);assert.ok(r.target.includes('3157'));assert.ok(!r.target.includes('1052'));const p=sequentialPurchases(r.target,s,data);assert.equal(p.steps.reduce((n,x)=>n+x.credit,0),data.items['3157'].gold.total+data.items['1052'].gold.total);});
test('scaling HP fragment follows level and movement fragment adds percentage',()=>{const s=initialScenario(data),f=s.player;f.runes.shards=[];const base=statsFor(f,data);f.runes.shards=['haste','scalingHP','hp'];const x=statsFor(f,data);assert.equal(x.hp-base.hp,10*f.level+65);assert.equal(x.haste-base.haste,8);});

test('new scenario opens with Jinx at level 18',()=>{const s=initialScenario(data);assert.equal(s.player.champion,'Jinx');assert.equal(s.player.level,18);assert.equal(s.enemy.level,18);});

test('15 to 85 percent defense changes Jinx and Shen full targets',()=>{for(const id of ['Jinx','Shen']){const s=initialScenario(data);s.player=fighter(data,id);s.weights={offense:85,defense:15,utility:0};const a=fullBuild(s,data);s.weights={offense:15,defense:85,utility:0};const b=fullBuild(s,data,'balanced',a.target);assert.notDeepEqual(a.target,b.target,id);assert.equal(b.target.length,6);}});
