import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import type {Dataset} from '../src/contracts.ts';import {parseKitSource,evaluateImportedImpact} from '../src/kitImport.ts';import {evaluateBuild,offensiveMetric} from '../src/buildEvaluation.ts';import {initialScenario,fighter} from '../src/model.ts';
const data:Dataset=JSON.parse(readFileSync(new URL('../public/data/pt_BR.json',import.meta.url),'utf8'));
// Synthetic coefficients test the parser/evaluator algebra; they are NOT Lulu gameplay values.
const source={version:data.version,champions:{Lulu:{abilities:{E:[{effects:[{leveling:[{attribute:'Magic Damage',modifiers:[{values:[10,20,30,40,50],units:['']},{values:[25],units:['% AP']}]}]}]},{effects:[{leveling:[{attribute:'Shield',modifiers:[{values:[20,30,40,50,60],units:['']},{values:[50],units:['% AP']}]}]}]}]}}}};
test('ingestion rejects absent or mismatched patches',()=>{assert.throws(()=>parseKitSource({},data,'fixture'),/Patch/);assert.throws(()=>parseKitSource({...source,version:'different'},data,'fixture'),/Patch/);});
test('imported coefficients retain condition boundaries and never auto-certify a kit',()=>{
 const imported=parseKitSource(source,data,'fixture'),kit=imported.champions.Lulu;assert.equal(Object.keys(imported.champions).length,Object.keys(data.champions).length);assert.equal(kit.isExactFormula,false);
 const damage=kit.impacts.find(i=>i.kind==='damage')!,shield=kit.impacts.find(i=>i.kind==='shield')!;assert.equal(damage.condition,'enemy');assert.equal(shield.condition,'ally');assert.deepEqual(damage.terms[1].values,[.25]);
 const stats={flat:1,ad:0,bonusAD:0,ap:100,hp:0,armor:0,mr:0,haste:0};assert.throws(()=>evaluateImportedImpact(damage,1,stats,'enemy'),/validada/);
 assert.equal(evaluateImportedImpact({...damage,reviewed:true},2,stats,'enemy'),45);assert.equal(evaluateImportedImpact({...damage,reviewed:true},2,stats,'ally'),0);assert.equal(evaluateImportedImpact({...shield,reviewed:true},2,stats,'ally'),80);assert.equal(evaluateImportedImpact({...shield,reviewed:true},2,stats,'enemy'),0);
});
test('unknown modifiers or conditions are quarantined instead of guessed',()=>{const raw=structuredClone(source);const entry=raw.champions.Lulu.abilities.E[0].effects[0].leveling[0];entry.modifiers[1].units=['% unknown stat'];const kit=parseKitSource(raw,data,'fixture').champions.Lulu;assert.ok(kit.impacts[0].missing.length);assert.throws(()=>evaluateImportedImpact({...kit.impacts[0],reviewed:true},1,{flat:1,ad:0,bonusAD:0,ap:100,hp:0,armor:0,mr:0,haste:0},'enemy'),/validada/);});
test('class DPS remains separate from the offensive attribute index and exact DPS stays unavailable',()=>{const s=initialScenario(data);s.player=fighter(data,'Lux');const m=evaluateBuild([],s,data);assert.equal(m.exactDPS,null);assert.equal(m.offenseBasis,'attribute-index');assert.ok((m.estimatedRotationDPS??0)>0);assert.equal(offensiveMetric(m),m.offenseValue);});
