import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import type {Dataset} from '../src/contracts.ts';import {initialScenario} from '../src/model.ts';import {reconcilePatch,loadPatch} from '../src/patchService.ts';import {fullBuild} from '../src/fullBuild.ts';
import {syncPatch,readJSON,INTERVAL} from '../server/patchSync.mjs';
const data:Dataset=JSON.parse(readFileSync(new URL('./fixtures/16.19.1-pt_BR.json',import.meta.url),'utf8'));
function environment(){const values=new Map<string,string>();return {values,env:{BUCKET:{async get(k:string){return values.has(k)?{json:async()=>JSON.parse(values.get(k)!)}:null;},async put(k:string,v:string){values.set(k,v);},async delete(k:string){values.delete(k);}},ASSETS:{async fetch(r:Request){return Response.json({...data,locale:r.url.includes('en_US')?'en_US':'pt_BR'});}}}};}
function upstream(version:string,fail=false){return async(input:unknown)=>{const url=String(input);if(url.endsWith('versions.json'))return Response.json([version]);if(url.endsWith('item.json'))return Response.json({version,data:data.items});if(url.endsWith('runesReforged.json'))return Response.json(data.runes);if(url.endsWith('/champion.json'))return Response.json({version,data:{Jinx:{id:'Jinx'}}});if(fail)throw Error('offline');return Response.json({data:{Jinx:data.champions.Jinx}});};}
test('server checks 12h cadence, retains last good catalog and skips redundant fetch',async()=>{const {env}=environment(),now=Date.now();let calls=0;const fetcher=async(input:unknown)=>{calls++;return upstream(data.version)(input);};const r=await syncPatch(env,'https://example.test',fetcher,now);assert.equal(r.status,'fresh');const again=await syncPatch(env,'https://example.test',fetcher,now+1000);assert.equal(again.status,'fresh');assert.equal(calls,1);await syncPatch(env,'https://example.test',fetcher,now+INTERVAL+1);assert.equal(calls,2);});
test('new patch published only after all detailed champions in both locales',async()=>{const {env}=environment(),now=Date.now();let r=await syncPatch(env,'https://example.test',upstream('16.20.1'),now);assert.equal(r.status,'updating');assert.equal((await readJSON(env.BUCKET,'patch/current.json')).version,data.version);r=await syncPatch(env,'https://example.test',upstream('16.20.1'),now+1);assert.equal(r.status,'updating');assert.equal((await readJSON(env.BUCKET,'patch/current.json')).version,data.version);r=await syncPatch(env,'https://example.test',upstream('16.20.1'),now+2);assert.equal(r.status,'updated');assert.equal((await readJSON(env.BUCKET,'patch/16.20.1/en_US.json')).champions.Jinx.spells.length,4);});
test('failed champion fetch leaves previous patch and resumable cursor intact',async()=>{const {env}=environment();await syncPatch(env,'https://example.test',upstream('16.20.1'));await assert.rejects(()=>syncPatch(env,'https://example.test',upstream('16.20.1',true)));assert.equal((await readJSON(env.BUCKET,'patch/current.json')).version,data.version);assert.equal((await readJSON(env.BUCKET,'patch/job.json')).cursor,0);});
test('patch reconciliation removes extinct IDs only, preserving matchup and configuration',()=>{const d=structuredClone(data);d.version='16.20.1';delete d.items['3072'];const s=initialScenario(data);s.player.items=['3072','3031'];s.player.owned=['3072'];s.player.locked=['3072'];s.player.runes.selected=[8008,99999];s.player.level=13;s.weights={offense:15,defense:85,utility:0};const before=structuredClone(s),r=reconcilePatch(s,d);assert.deepEqual(s,before);assert.deepEqual(r.scenario.player.items,['3031']);assert.deepEqual(r.scenario.player.runes.selected,[8008]);assert.equal(r.scenario.player.champion,s.player.champion);assert.equal(r.scenario.player.level,13);assert.deepEqual(r.scenario.weights,s.weights);assert.deepEqual(r.scenario.enemy,s.enemy);assert.deepEqual(r.scenario.player.skills,s.player.skills);assert.equal(fullBuild(r.scenario,d).target.length,6);});
test('browser fallback loads bundled last good catalog without resetting scenario',async()=>{const original=globalThis.fetch;globalThis.fetch=async(input)=>{if(String(input).startsWith('https://'))throw Error('offline');return Response.json(data);};try{const r=await loadPatch('pt_BR');assert.equal(r.data.version,data.version);assert.equal(r.state.fallback,true);}finally{globalThis.fetch=original;}});
