import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';
test('SQL migrations, RLS, trial, roles, sharing, webhook idempotence',async(t)=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
 for(const file of ['202610010001_foundation.sql','202610010002_billing.sql'])await db.exec(readFileSync(new URL(`../supabase/migrations/${file}`,import.meta.url),'utf8'));
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';await db.exec(`insert into auth.users values('${a}','a@test.invalid'),('${b}','b@test.invalid');`);
 async function as(id:string){await db.exec(`reset role;set request.jwt.claim.sub='${id}';set role authenticated;`);}
 await as(a);
 await t.test('new user free; direct role mutation denied',async()=>{const r=await db.query<{e:{pro:boolean}}>('select public.my_entitlement() e');assert.equal(r.rows[0].e.pro,false);await assert.rejects(()=>db.exec("update public.accounts set role='owner'"),/permission denied/);});
 await t.test('trial starts exactly once for 14 days',async()=>{await db.exec('select public.activate_trial()');const r=await db.query<{days:string;pro:boolean}>(`select extract(epoch from trial_end-trial_started_at)/86400 days from public.accounts`);assert.equal(Number(r.rows[0].days),14);await assert.rejects(()=>db.exec('select public.activate_trial()'),/already activated/);});
 await t.test('own scenario CRUD and other-owner RLS isolation',async()=>{await db.exec(`insert into public.scenarios(owner_id,name,patch,payload) values('${a}','test','16.19.1','{"schema":1}')`);await as(b);assert.equal((await db.query('select * from public.scenarios')).rows.length,0);await assert.rejects(()=>db.exec(`insert into public.scenarios(owner_id,name,patch,payload) values('${a}','stolen','x','{}')`),/row-level security/);await as(a);assert.equal((await db.query('select * from public.scenarios')).rows.length,1);});
 await t.test('normal user cannot access admin or change billing',async()=>{await assert.rejects(()=>db.exec('select public.admin_overview()'),/Forbidden/);await assert.rejects(()=>db.exec(`select public.admin_configure_billing('{"provider":"stripe","enabled":false}')`),/Forbidden/);});
 await t.test('share reveals payload without owner identity, and can be revoked',async()=>{const row=await db.query<{id:string}>('select id from public.scenarios limit 1');const token=await db.query<{token:string}>('select public.create_share($1) token',[row.rows[0].id]);await db.exec('reset role;set role anon;');const shared=await db.query<{s:Record<string,unknown>}>('select public.read_shared($1) s',[token.rows[0].token]);assert.ok(shared.rows[0].s.payload);assert.equal(shared.rows[0].s.owner_id,undefined);await as(a);await db.query('select public.revoke_share($1)',[token.rows[0].token]);assert.equal((await db.query<{s:unknown}>('select public.read_shared($1) s',[token.rows[0].token])).rows[0].s,null);});
 await t.test('owner access uses server role and audit writes succeed',async()=>{await db.exec(`reset role;update public.accounts set role='owner' where id='${a}';`);await as(a);const r=await db.query<{e:{pro:boolean}}> ('select public.my_entitlement() e');assert.equal(r.rows[0].e.pro,true);await db.exec(`select public.admin_configure_billing('{"provider":"stripe","enabled":false,"sandbox_approved":false}')`);assert.ok((await db.query('select public.admin_overview()')).rows.length);});
 await t.test('authenticated client cannot grant subscriptions',async()=>{await assert.rejects(()=>db.exec(`select public.apply_billing_event('stripe','ev','h','${a}','sub','active',now()+interval '1 month')`),/permission denied/);});
 await t.test('server payment processing atomic and idempotent',async()=>{await db.exec(`reset role;set role service_role;select public.apply_billing_event('stripe','ev1','hash','${b}','sub1','active',now()+interval '1 month');select public.apply_billing_event('stripe','ev1','hash','${b}','sub1','active',now()+interval '1 month');`);assert.equal((await db.query('select * from public.webhook_events')).rows.length,1);assert.equal((await db.query('select * from public.subscriptions')).rows.length,1);await as(b);const r=await db.query<{e:{pro:boolean}}>('select public.my_entitlement() e');assert.equal(r.rows[0].e.pro,true);});
 await t.test('reconciliation of cancelled subscription removes paid access',async()=>{await db.exec(`reset role;set role service_role;select public.apply_billing_event('stripe','ev2','hash2','${b}','sub1','canceled',null);`);await as(b);const r=await db.query<{e:{pro:boolean}}>('select public.my_entitlement() e');assert.equal(r.rows[0].e.pro,false);});
 await db.close();
});
