export const RIOT='https://ddragon.leagueoflegends.com';
export const INTERVAL=12*60*60*1000;
const LOCALES=['pt_BR','en_US'];
export async function readJSON(bucket,key){const o=await bucket.get(key);return o?o.json():null;}
export async function putJSON(bucket,key,value){await bucket.put(key,JSON.stringify(value),{httpMetadata:{contentType:'application/json'}});}
async function getJSON(url,fetcher){const r=await fetcher(url,{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error(`Riot HTTP ${r.status}`);return r.json();}
export function validateDataset(d){if(!/^\d+\.\d+\.\d+$/.test(d?.version??'')||!Object.keys(d.champions??{}).length||!Object.keys(d.items??{}).length||!Array.isArray(d.runes)||d.runes.length<2)throw Error('Catálogo incompleto');for(const c of Object.values(d.champions)){if(!c.stats||!Array.isArray(c.spells)||c.spells.length!==4||!Array.isArray(c.skins)||!c.passive)throw Error('Detalhes de campeão incompletos');}}
export async function initialize(env,origin){let current=await readJSON(env.BUCKET,'patch/current.json');if(current)return current;const data=await Promise.all(LOCALES.map(async locale=>{const r=await env.ASSETS.fetch(new Request(`${origin}/data/${locale}.json`));if(!r.ok)throw Error('Snapshot inicial ausente');const d=await r.json();validateDataset(d);return d;}));if(data[0].version!==data[1].version)throw Error('Snapshots divergentes');for(const d of data)await putJSON(env.BUCKET,`patch/${d.version}/${d.locale}.json`,d);current={version:data[0].version,checkedAt:null,generatedAt:data[0].generatedAt,source:RIOT};await putJSON(env.BUCKET,'patch/current.json',current);return current;}
/** Bounded, resumable updater: publish pointer only after both locales have every detailed champion. */
export async function syncPatch(env,origin,fetcher=fetch,now=Date.now()){
 const current=await initialize(env,origin),job=await readJSON(env.BUCKET,'patch/job.json');
 if(!job&&current.checkedAt&&now-Date.parse(current.checkedAt)<INTERVAL)return {status:'fresh',...current};
 if(job){const locale=LOCALES[job.localeIndex],d=await readJSON(env.BUCKET,`staging/${job.version}/${locale}.json`);if(!d)throw Error('Staging ausente');const ids=job.ids[locale],batch=ids.slice(job.cursor,job.cursor+12);const details=await Promise.all(batch.map(async id=>{const raw=await getJSON(`${RIOT}/cdn/${job.version}/data/${locale}/champion/${id}.json`,fetcher);const c=raw.data?.[id];if(!c?.spells||c.spells.length!==4)throw Error('Champion inválido');return [id,c];}));for(const [id,c] of details)d.champions[id]=c;await putJSON(env.BUCKET,`staging/${job.version}/${locale}.json`,d);job.cursor+=batch.length;if(job.cursor>=ids.length){validateDataset(d);await putJSON(env.BUCKET,`patch/${job.version}/${locale}.json`,d);job.localeIndex++;job.cursor=0;}if(job.localeIndex>=LOCALES.length){const versions=await getJSON(`${RIOT}/api/versions.json`,fetcher);if(versions[0]!==job.version){await env.BUCKET.delete('patch/job.json');return {status:'retry',version:current.version};}const next={version:job.version,checkedAt:new Date(now).toISOString(),generatedAt:job.startedAt,source:RIOT};await putJSON(env.BUCKET,'patch/current.json',next);await env.BUCKET.delete('patch/job.json');return {status:'updated',...next};}await putJSON(env.BUCKET,'patch/job.json',job);return {status:'updating',version:current.version,pendingVersion:job.version,locale:LOCALES[job.localeIndex],cursor:job.cursor};}
 const versions=await getJSON(`${RIOT}/api/versions.json`,fetcher),version=versions[0];if(!/^\d+\.\d+\.\d+$/.test(version??''))throw Error('Versão Riot inválida');
 if(version===current.version){const next={...current,checkedAt:new Date(now).toISOString()};await putJSON(env.BUCKET,'patch/current.json',next);return {status:'fresh',...next};}
 const ids={};for(const locale of LOCALES){const [catalog,items,runes]=await Promise.all(['champion','item','runesReforged'].map(key=>getJSON(`${RIOT}/cdn/${version}/data/${locale}/${key}.json`,fetcher)));if(catalog.version!==version||items.version!==version||!catalog.data||!items.data||!Array.isArray(runes))throw Error('Patch inconsistente');ids[locale]=Object.keys(catalog.data);await putJSON(env.BUCKET,`staging/${version}/${locale}.json`,{version,locale,generatedAt:new Date(now).toISOString(),source:`${RIOT}/cdn/${version}/data/${locale}/`,champions:{},items:items.data,runes});}
 const nextJob={version,ids,localeIndex:0,cursor:0,startedAt:new Date(now).toISOString()};await putJSON(env.BUCKET,'patch/job.json',nextJob);return {status:'updating',version:current.version,pendingVersion:version,cursor:0};
}
