'use client';
import {useState} from 'react';
import type {Dataset,Fighter,SkillKey} from './contracts';
import {tooltipFor,type FormulaOverride,type TooltipOverrides} from './abilityTooltip';
import {Modal} from './components';
const numeric=(v:number|string|null)=>v===null?'Não fornecido':typeof v==='number'?v.toLocaleString('pt-BR',{maximumFractionDigits:2}):v;
export default function AbilityTooltip({f,data,canEdit=false,onlyKey}:{f:Fighter;data:Dataset;canEdit?:boolean;onlyKey?:SkillKey}){
 const [active,setActive]=useState<'P'|SkillKey|null>(null),[pinned,setPinned]=useState(false),[overrides,setOverrides]=useState<TooltipOverrides>({}),[dev,setDev]=useState(false),[variable,setVariable]=useState('');
 const [draft,setDraft]=useState<FormulaOverride>({base:0,ad:0,bonusAD:0,ap:0,hp:0,armor:0,mr:0});const c=data.champions[f.champion];
 const m=active?tooltipFor(f,data,active,overrides):null;
 return <div className="ability-inspector" onMouseLeave={()=>{if(!pinned&&!dev)setActive(null);}}>
 <div className="ability-icons">{(onlyKey?[onlyKey]:['P','Q','W','E','R'] as const).map((key)=>{const spell=key==='P'?c.passive:c.spells[['Q','W','E','R'].indexOf(key)];return <button key={key} className={active===key?'active-ability':''} aria-label={`Detalhes de ${key}: ${spell.name}`} aria-expanded={active===key} onMouseEnter={()=>{if(!pinned)setActive(key);}} onFocus={()=>setActive(key)} onClick={()=>{setActive(key);setPinned(true);}}><img src={`/assets/riot/icons/${key==='P'?'passive':'spell'}/${spell.image.full}`} alt="" onError={e=>{e.currentTarget.style.opacity='.15';}}/><span>{key}</span></button>;})}</div>
 {m&&<section className="lol-tooltip" role="region" aria-label={`Tooltip ${m.name}`}><div className="tooltip-heading"><div><strong>{m.name}</strong><small>{active==='P'?'Passiva':`Rank ${m.rank||'não evoluído'} · ${m.custom?'Simulação personalizada':'Dados do snapshot'}`}</small></div><span>{m.cost===null?'—':numeric(m.cost)} {m.resource}<br/>{m.cooldown===null?'—':numeric(m.cooldown)+'s'} de recarga</span><button aria-label="Fechar tooltip" onClick={()=>{setActive(null);setPinned(false);}}>×</button></div><p className="tooltip-description">{m.parts.map((part,i)=><span key={i} className={`tooltip-${part.color} ${part.status==='missing'?'tooltip-unresolved':''}`}>{part.text}</span>)}</p>{m.rows.length>0&&<div className="tooltip-table"><table><thead><tr><th>Atributo</th>{Array.from({length:c.spells[['Q','W','E','R'].indexOf(active as SkillKey)]?.maxrank??0},(_,i)=><th key={i}>Nv. {i+1}</th>)}</tr></thead><tbody>{m.rows.map((row,i)=><tr key={i}><th>{row.label}</th>{row.values.map((value,k)=><td className={m.rank===k+1?'tooltip-current':''} key={k}>{numeric(value)}</td>)}</tr>)}</tbody></table></div>}{m.leveltip.length>0&&<details><summary>Progressão informada pela API</summary>{m.leveltip.map((tip,i)=><p key={i}>{tip.label}: {tip.value}</p>)}</details>}<details><summary>Cobertura da descrição · {m.warnings.length} notas</summary>{m.warnings.map((w,i)=><p key={i}>{w}</p>)}<p>Valores brutos, antes da mitigação do alvo. Condições e efeitos completos da habilidade podem não estar simulados.</p></details>{canEdit&&active!=='P'&&<button onClick={()=>setDev(true)}>Override de fórmula · Admin</button>}</section>}
 {dev&&canEdit&&<Modal title="Override local · Simulação personalizada" close={()=>setDev(false)}><p>Não altera a fórmula oficial nem as permissões da conta. Coeficientes são frações: 0,6 = 60%. Não há execução de código.</p><label className="field"><span>Variável do tooltip</span><input value={variable} onChange={e=>setVariable(e.target.value.replace(/[^a-z0-9]/gi,''))}/></label><div className="three-fields">{Object.entries(draft).map(([k,v])=><label className="field" key={k}><span>{k}</span><input type="number" min="0" step="0.01" value={v} onChange={e=>setDraft({...draft,[k]:Math.max(0,Math.min(100000,Number(e.target.value)))})}/></label>)}</div><button disabled={!variable} onClick={()=>{setOverrides({...overrides,[`${f.champion}:${active}:${variable.toLowerCase()}`]:draft});setDev(false);}}>Aplicar override local</button><button onClick={()=>{setOverrides({});setDev(false);}}>Restaurar padrão do patch</button></Modal>}
 </div>;
}
