'use client';
import type {Scenario} from './contracts';
import {normalizeWeights} from './model';
import PreferenceSlider from './PreferenceSlider';
import AttributeLabel from './AttributeLabel';
const n=(value:number)=>value.toLocaleString('pt-BR',{maximumFractionDigits:0});
export default function BuildControls({scenario:s,total,remaining,onChange,onCommit}:{scenario:Scenario;total:number;remaining:number;onChange:(patch:Partial<Scenario>)=>void;onCommit:()=>void}){
 return <section className="build-controls" aria-label="Controles da meta de build"><div className="build-control-preference"><label htmlFor="build-preference">Preferência de atributos</label><div className="build-control-labels"><AttributeLabel attribute="damage">Dano {n(s.weights.offense)}%</AttributeLabel><AttributeLabel attribute="defense">Defesa {n(s.weights.defense)}%</AttributeLabel></div><PreferenceSlider id="build-preference" aria-label="Preferência de atributos" min={0} max={100} dir="rtl" step={1} value={s.weights.offense+s.weights.defense>0?Math.round(s.weights.offense/(s.weights.offense+s.weights.defense)*100):50} onValue={offense=>onChange({weights:{offense:offense*(100-s.weights.utility)/100,defense:(100-offense)*(100-s.weights.utility)/100,utility:s.weights.utility},customPreference:false})} onCommit={onCommit}/><label>Utilidade {n(s.weights.utility)}%<PreferenceSlider aria-label="Preferência de utilidade" min={0} max={100} value={s.weights.utility} onValue={value=>onChange({weights:normalizeWeights(s.weights,'utility',value),customPreference:true})} onCommit={onCommit}/></label><small>Cada 1% recalcula a build, incluindo bota e core automáticos. Travas e itens possuídos são respeitados.</small></div><label className="build-control-gold"><AttributeLabel attribute="gold">Ouro disponível</AttributeLabel><input aria-label="Ouro disponível" type="number" min={0} max={100000} value={s.budget} onChange={e=>onChange({budget:Math.max(0,Math.min(100000,Number(e.target.value)||0))})}/></label><label className="build-control-window"><AttributeLabel attribute="window">Janela (s)</AttributeLabel><input aria-label="Janela de combate" type="number" min={1} max={120} value={s.duration} onChange={e=>onChange({duration:Math.max(1,Math.min(120,Number(e.target.value)||1))})}/></label><div className="build-control-metric"><AttributeLabel attribute="gold">Custo total · 6 slots</AttributeLabel><strong>{n(total)} G</strong></div><div className="build-control-metric"><AttributeLabel attribute="gold">Saldo após compras</AttributeLabel><strong>{n(remaining)} G</strong></div></section>;
}
