'use client';
import {useEffect,useId,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ChevronDown,Search,Check} from 'lucide-react';
import type {Dataset} from './contracts';
const clean=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export default function ChampionPicker({data,value,label,onChange,empty=false,emptyLabel='Não selecionado',emptyValue=''}:{data:Dataset;value:string;label:string;onChange:(value:string)=>void;empty?:boolean;emptyLabel?:string;emptyValue?:string}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0),[position,setPosition]=useState({left:0,width:280,top:0,bottom:undefined as number|undefined,height:360});
 const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),id=useId(),selected=data.champions[value];
 const options=useMemo(()=>[...(empty?[{id:emptyValue,name:emptyLabel,image:null}]:[]),...Object.values(data.champions).sort((a,b)=>a.name.localeCompare(b.name)).map(c=>({id:c.id,name:c.name,image:c.image.full}))].filter(c=>clean(c.name).includes(clean(query))),[data,query,empty,emptyValue,emptyLabel]);
 const choose=(value:string)=>{onChange(value);setOpen(false);trigger.current?.focus();};
 const show=()=>{setQuery('');setActive(0);setOpen(true);};
 useLayoutEffect(()=>{if(!open)return;const locate=()=>{const a=trigger.current?.getBoundingClientRect();if(!a)return;const below=innerHeight-a.bottom-14,above=a.top-14,up=below<200&&above>below;setPosition({left:Math.max(8,Math.min(a.left,innerWidth-Math.max(a.width,240)-8)),width:Math.min(Math.max(a.width,240),innerWidth-16),top:up?0:a.bottom+6,bottom:up?innerHeight-a.top+6:undefined,height:Math.max(100,Math.min(360,up?above:below))});};locate();input.current?.focus();const dismiss=(e:PointerEvent)=>{if(!trigger.current?.contains(e.target as Node)&&!menu.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',dismiss);window.addEventListener('resize',locate);window.addEventListener('scroll',locate,true);return()=>{document.removeEventListener('pointerdown',dismiss);window.removeEventListener('resize',locate);window.removeEventListener('scroll',locate,true);};},[open]);
 useEffect(()=>{if(open)document.getElementById(`${id}-option-${active}`)?.scrollIntoView({block:'nearest'});},[active,open,id]);
 return <div className="field champion-picker"><span id={`${id}-label`}>{label}</span><button ref={trigger} type="button" role="combobox" aria-labelledby={`${id}-label`} aria-expanded={open} aria-controls={`${id}-list`} aria-haspopup="listbox" className="champion-picker-trigger" onClick={()=>open?setOpen(false):show()} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();show();}}}>{selected?<img src={`/assets/riot/icons/champion/${selected.image.full}`} alt=""/>:<span className="champion-picker-unknown" aria-hidden="true">?</span>}<strong>{selected?.name??emptyLabel}</strong><ChevronDown size={14}/></button>{open&&createPortal(<div ref={menu} className="champion-picker-menu" style={{left:position.left,width:position.width,top:position.bottom===undefined?position.top:undefined,bottom:position.bottom,maxHeight:position.height}}><div className="champion-picker-search"><Search size={15}/><input ref={input} value={query} placeholder="Buscar campeão…" aria-label={`Buscar: ${label}`} aria-controls={`${id}-list`} aria-activedescendant={options.length?`${id}-option-${active}`:undefined} onChange={e=>{setQuery(e.target.value);setActive(0);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);trigger.current?.focus();}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setActive(n=>Math.max(0,Math.min(options.length-1,n+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'){e.preventDefault();if(options[active])choose(options[active].id);}else if(e.key==='Tab')setOpen(false);}}/></div><div id={`${id}-list`} role="listbox" aria-labelledby={`${id}-label`} className="champion-picker-list">{options.map((c,i)=><button type="button" role="option" aria-selected={value===c.id} id={`${id}-option-${i}`} key={c.id} tabIndex={-1} className={active===i?'is-active':''} onPointerMove={()=>setActive(i)} onClick={()=>choose(c.id)}>{c.image?<img loading="lazy" src={`/assets/riot/icons/champion/${c.image}`} alt=""/>:<span className="champion-picker-unknown" aria-hidden="true">?</span>}<span>{c.name}</span>{value===c.id&&<Check size={14}/>}</button>)}{!options.length&&<p className="champion-picker-empty">Nenhum campeão encontrado.</p>}</div></div>,document.body)}</div>;
}
