'use client';
import {useMemo,useState} from 'react';
import type {Dataset,Scenario,DraftState} from './contracts';
import {contextualRecommendation,applyCounter} from './contextRecommendations';
import ItemTooltip from './ItemTooltip';
import {RuneCard} from './RuneProfile';
import {fullBuild} from './fullBuild';
import {fighter,plain} from './model';
import {normalizeDraft,DRAFT_LANES} from './draft';
const roles=['Topo','Selva','Meio','Atirador','Suporte'],cdn='/assets/riot';
export default function ContextAssistant({scenario:s,data,onChange,composition}:{composition?:DraftState;scenario:Scenario;data:Dataset;onChange:(s:Scenario)=>void}){
 const [selectedMode,setMode]=useState<'matchup'|'draft'>(composition?'draft':'matchup'),[error,setError]=useState('');
 const mode=s.matchupUnknown?'draft':selectedMode;
 const draft=composition??normalizeDraft(s,data);
 const id=mode==='matchup'?s.player.champion:draft.own[draft.active]||s.player.champion,enemies=mode==='matchup'?[s.enemy.champion]:draft.enemy;
 const rec=useMemo(()=>contextualRecommendation(s,data,id,enemies,mode==='matchup'?'Matchup 1v1':'Draft 5v5',mode,mode==='draft'?DRAFT_LANES[draft.active]:undefined),[s,data,id,JSON.stringify(enemies),mode]);
 const current=id===s.player.champion?s.player:{...fighter(data,id),level:s.player.level};
 const active=mode==='draft'?{...current,lane:DRAFT_LANES[draft.active]}:current,runes=data.runes.flatMap(t=>t.slots.flatMap(row=>row.runes)),options=Object.values(data.champions).sort((a,b)=>a.name.localeCompare(b.name));
 const setDraft=(patch:Partial<DraftState>)=>onChange({...s,draft:{...draft,...patch}});
 const selectors=(side:'own'|'enemy')=><div className="draft-slots">{draft[side].map((champ,index)=><div className={`draft-slot ${side==='own'&&draft.active===index?'active':''}`} key={index}><button aria-label={`Ver ${roles[index]}: ${data.champions[champ]?.name}`} onClick={()=>side==='own'&&setDraft({active:index})}><img src={`${cdn}/icons/champion/${data.champions[champ].image.full}`} alt=""/><span>{roles[index]}</span></button><select aria-label={`${side==='own'?'Aliado':'Inimigo'} ${roles[index]}`} value={champ} onChange={e=>setDraft({[side]:draft[side].map((old,i)=>i===index?e.target.value:old)})}>{options.map(c=><option key={c.id} value={c.id} disabled={draft[side].some((id,i)=>i!==index&&id===c.id)}>{c.name}</option>)}</select></div>)}</div>;
 return <section className="context-assistant"><div className="context-heading"><div><span className="quick-eyebrow">INTELIGÊNCIA CONTEXTUAL</span><h2>Itens e runas para seu confronto.</h2></div><div className="context-tabs"><button disabled={s.matchupUnknown} title={s.matchupUnknown?'Escolha o adversário da lane para usar o modo 1v1.':undefined} aria-pressed={mode==='matchup'} onClick={()=>setMode('matchup')}>Contra sua lane</button><button aria-pressed={mode==='draft'} onClick={()=>setMode('draft')}>Contra o time inimigo</button></div></div>
 {mode==='draft'&&!composition&&<details open><summary>Composição e campeão ativo</summary><h3>Quem é você no draft? Clique no retrato.</h3>{selectors('own')}<h3>Time adversário</h3>{selectors('enemy')}</details>}
 <div className="context-summary"><strong>Sugestão · {data.champions[id].name} · {roles[draft.active]}</strong><span>{mode==='matchup'?`vs ${data.champions[s.enemy.champion].name}`:`${Math.round(rec.analysis.physical*100)}% físico / ${Math.round(rec.analysis.magic*100)}% mágico · estimativa por perfis`}</span></div>
 {!composition&&<div aria-live="polite" className="context-threats"><span>CC duro: {rec.analysis.hardCC}/{rec.analysis.count}</span><span>Tanques: {rec.analysis.tanks}</span><span>Burst: {rec.analysis.burst}</span></div>}
 <div className="counter-grid"><div><h3>2 itens-chave</h3>{rec.items.map(item=><ItemTooltip key={item} id={item} f={active} data={data} context="Counter contextual · inventário ativo" pinOnClick><button className="counter-choice"><img src={`${cdn}/icons/item/${data.items[item].image.full}`} alt=""/><span>{plain(data.items[item].name)}</span></button></ItemTooltip>)}</div><div><h3>2 runas-chave</h3>{rec.runes.map(rid=>{const r=runes.find(r=>r.id===rid)!;return <RuneCard key={rid} r={r} f={active} data={data}/>;})}</div></div>
 <p>{rec.explanation}</p><div className="context-actions"><button disabled={mode==='matchup'?s.matchupUnknown:!draft.own[draft.active]||!draft.enemy.some(Boolean)} onClick={()=>{let preset=applyCounter(mode==='draft'?{...s,draft}:s,data,rec.preset);if(composition)preset={...preset,draft:composition,enemyTeam:[...composition.enemy],allies:composition.own.filter((_,i)=>i!==composition.active)};const required=new Set([...preset.player.locked,...(!s.allowSell?preset.player.owned:[])].filter(id=>data.items[id]?.gold.total>=2000));if(required.size>(rec.preset.boot?5:6)){setError('Libere uma trava ou um item possuído para aplicar este counter.');return;}try{fullBuild(preset,data);onChange(preset);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}}>Aplicar Counter Ideal</button>{s.counterPreset&&<button onClick={()=>onChange({...s,counterPreset:undefined})}>Remover preset</button>}<small>{s.counterPreset?`Preset ativo: ${s.counterPreset.source}`:'Prévia independente · aplica contexto e runas; itens competem pelo score do slider.'}</small></div>{error&&<p role="alert">{error}</p>}
 <details><summary>Critérios e cobertura</summary>{rec.warnings.map(w=><p key={w}>{w}</p>)}<p>O preset avalia atributos e tags em tempo de execução, somente para os adversários selecionados. As prioridades são heurísticas, sem estatísticas de vitória. As habilidades e a preferência manual permanecem preservadas. Campeão e rota seguem a seleção do laboratório.</p></details></section>;
}
