'use client';
import {useMemo} from 'react';
import type {Dataset,Scenario,SkillKey} from './contracts';
import type {QuickRecommendation} from './recommendation';
import {plain,conservative} from './model';
import {championKitCoverage} from './championKit';
import {itemReason} from './fullBuild';
import {guideMatchups,guideAllies,skillUsage} from './contextGuide';
import GateKeepPro from './auth/GateKeepPro';
const num=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:3});
export default function ContextGuide({scenario:s,data,recommendation:rec}:{scenario:Scenario;data:Dataset;recommendation:QuickRecommendation}){
 const c=data.champions[s.player.champion],coverage=championKitCoverage(c.id,data);
 const matchups=useMemo(()=>guideMatchups(s,data),[s.player.champion,s.player.lane,data]);
 const allies=useMemo(()=>guideAllies(s,data),[s.player.champion,s.player.lane,data]);
 const sequence=s.player.skills.length?s.player.skills:conservative(data,c.id);
 const priority=(['Q','W','E'] as SkillKey[]);
 // Priority comes from the configured path: first skill reaching rank five, then current ranks.
 priority.sort((a,b)=>{const nth=(key:SkillKey)=>{const indices=sequence.map((v,i)=>v===key?i:-1).filter(i=>i>=0);return indices[4]??99;};return nth(a)-nth(b)||sequence.filter(v=>v===b).length-sequence.filter(v=>v===a).length;});
 const round=rec.decisions?.[0];
 const excluded=round?.candidates.filter(row=>!rec.target.includes(row.id)&&row.score<round.candidates[0].score-1e-9).slice(0,3)??[];
 return <section className="panel contextual-guide" aria-label="Guia contextual do campeão"><div className="panel-head"><div><span className="quick-eyebrow">GUIA CONTEXTUAL · {s.player.lane}</span><h2>Entenda {c.name}</h2></div><span className="testing-tag">{coverage.isExactFormula?'Guia Refinado & Validado':'Estimativa de Kit'}</span></div><p className="hint">Análise de Sinergia de Kit (Calculador Aegis). {coverage.status==='partial'?'Há fórmulas parciais disponíveis; isso não valida o kit completo nem este guia.':'Textos dinâmicos por perfil e catálogo; interações específicas ainda exigem revisão.'} Estatísticas locais/globais de partidas: não integradas.</p>
 <nav className="guide-nav" aria-label="Seções do guia">{[['skills','Habilidades'],['items','Itens'],['matchups','Matchups'],['synergies','Sinergias']].map(([id,label])=><a key={id} href={`#guide-${id}`}>{label}</a>)}</nav>
 <section id="guide-skills"><h3>Ordem e uso de habilidades</h3><p>Prioridade do caminho configurado: <strong>{sequence.length?priority.join(' → '):'Adapter especial pendente'}</strong>. R segue o caminho abaixo; isto não é uma ordem de meta observada.</p><div className="skill-scroll"><table className="skill-table"><thead><tr><th>Nível</th>{Array.from({length:18},(_,i)=><th key={i}>{i+1}</th>)}</tr></thead><tbody><tr><th>Path</th>{Array.from({length:18},(_,i)=><td key={i}>{sequence[i]??'—'}</td>)}</tr></tbody></table></div>{c.spells.map((sp,i)=>{const key=['Q','W','E','R'][i],usage=skillUsage(sp.description);return <details className="guide-card" key={key}><summary><img src={`/assets/riot/icons/spell/${sp.image.full}`} alt=""/><strong>{key} · {sp.name}</strong></summary><p>{plain(sp.description)}</p><p className="hint">Orientação dinâmica pelo texto do catálogo; não valida interações específicas.</p><p><strong>Momento de uso:</strong> {usage.moment}</p><GateKeepPro><div className="guide-advanced"><span className="pro-small">PRO · Dicas de execução estimadas</span><p><strong>Posicionamento:</strong> {usage.position}</p><p><strong>Erro comum:</strong> {usage.mistake}</p><p>Compare no editor a sequência com e sem esta ação. Tempos de animação, resets e combos especiais não são inferidos só pela descrição.</p>{c.id==='Shen'&&<p>{key==='Q'?'Observe a posição da espada e procure puxá-la através do adversário para aproveitar o fortalecimento descrito no kit.':key==='W'?'Reserve a zona de proteção para a janela de ataques inimigos; não trate o bloqueio de ataques como imunidade a toda habilidade.':key==='E'?'Prepare a trajetória da entrada e confirme acompanhamento do aliado; errar o controle deixa você exposto.':'Antes de canalizar, confira risco de interrupção e a situação da sua própria rota; proteger um aliado exige avaliar também o custo de abandonar a lane.'} Dica editorial baseada na descrição do kit; não é validação de combo.</p>}</div></GateKeepPro></details>;})}</section>
 <section id="guide-items"><h3>Por que estes itens?</h3><p className="hint">Dano {s.weights.offense}% · Defesa {s.weights.defense}% · Utilidade {s.weights.utility}%. Core e bota podem ser fixos; slots livres usam comparação gulosa contextual.</p><div className="guide-item-grid">{rec.target.map((id,i)=>{const decision=rec.decisions?.find(d=>d.selected===id),row=decision?.candidates.find(r=>r.id===id);return <article className="guide-card" key={id}><h4><img src={`/assets/riot/icons/item/${data.items[id].image.full}`} alt=""/>{plain(data.items[id].name)}</h4><small>{id===rec.boots?'Bota contextual':row?'Slot livre / situacional':'Core ou inventário preservado'} · {num(data.items[id].gold.total)} G</small><p>{rec.reasons[id]}</p><p>{itemReason(id,data)}</p>{row?<p className="hint">Score no slot {i+1}: {num(row.score)} = {num(s.weights.offense/100)} × {num(row.normalizedOffense)} (ofensiva) + {num(s.weights.defense/100)} × {num(row.normalizedEHP)} (EHP) + {num(s.weights.utility/100)} × {num(row.normalizedUtility)} (utilidade) + {num(row.counterBonus)} (contexto).</p>:<p className="hint">Preservado por regra estrutural ou inventário; não foi o vencedor de um ranking livre neste slot.</p>}</article>;})}</div><p className="hint">Motivos estratégicos podem citar efeitos de itens ainda não simulados. Scores usam apenas atributos/efeitos modelados, normalizados no pool de cada slot; não compare scores de slots diferentes.</p>
 <details className="guide-card"><summary>Itens que Parecem Bons, mas Não São <span className="pro-small">PRO</span></summary><GateKeepPro><p>“Armadilha” aqui significa menor prioridade neste cenário, não um item sempre ruim. Todos continuam sujeitos às mesmas regras de elegibilidade do montador.</p>{excluded.map(row=>{const best=round!.candidates[0];return <article key={row.id}><h4>{plain(data.items[row.id].name)}</h4><p>{itemReason(row.id,data)}</p><p>No primeiro slot livre avaliado: score {num(row.score)} contra {num(best.score)} de {plain(data.items[best.id].name)}. Diferença: {num(best.score-row.score)}.</p><p className="hint">Decomposição: ofensiva {num(row.normalizedOffense)}; EHP {num(row.normalizedEHP)}; utilidade {num(row.normalizedUtility)}; contra-bônus {num(row.counterBonus)}. Menor pontuação ponderada significa abrir mão de atributos mais valorizados pelos seus pesos neste pool.</p></article>;})}{!excluded.length&&<p>Não há alternativa com score inferior disponível na primeira decisão livre deste cenário.</p>}<p className="hint">Stacking futuro, waveclear real e valor de primeiro item não são integralmente simulados. Por isso, não atribuímos a Coração de Aço uma penalidade matemática de waveclear inexistente no modelo. Mudar o slider, a rota ou o matchup pode mudar este ranking.</p></GateKeepPro></details></section>
 <section id="guide-matchups"><h3>Matchups por características</h3><span className="testing-tag">Calculador Aegis · heurística de kit</span><p className="hint">Universo do catálogo, sem filtro de popularidade por rota. Índice de pressão descritivo: não é taxa de vitória ou resultado de duelo completo.</p><div className="guide-item-grid">{[['Mais difíceis',matchups.hard],['Mais favoráveis',matchups.best]].map(([title,rows])=><div key={title as string}><h4>{title as string}</h4>{(rows as typeof matchups.hard).map(row=><article className="guide-card" key={row.id}><h4><img src={`/assets/riot/icons/champion/${data.champions[row.id].image.full}`} alt=""/>{data.champions[row.id].name}</h4><p>Índice de pressão: {row.pressure}</p><details><summary>Por que aparece aqui? <span className="pro-small">PRO</span></summary><GateKeepPro>{row.reasons.map(text=><p key={text}>{text}</p>)}</GateKeepPro></details></article>)}{!(rows as typeof matchups.hard).length&&<p>O modelo não identifica vantagem suficiente para listar campeões nesta categoria.</p>}</div>)}</div><details className="guide-card"><summary>Critérios de análise aprofundada <span className="pro-small">PRO</span></summary><GateKeepPro><p>Pressão: maior alcance básico +1; burst contra perfil sem tanque +2; CC duro +1; tanque contra seu burst +2; sua durabilidade contra burst −2; seu controle contra burst −1. Somamos apenas características disponíveis. Habilidades de mobilidade, alcance de feitiços e execução podem inverter a leitura.</p><p>Considere o adversário real no simulador e configure seu combo para analisar dano e sobrevivência. Não há dados locais/globais de partidas conectados.</p></GateKeepPro></details></section>
 <section id="guide-synergies"><h3>Campeões que podem complementar seu kit</h3><div className="guide-item-grid">{allies.map(row=><article className="guide-card" key={row.id}><h4><img src={`/assets/riot/icons/champion/${data.champions[row.id].image.full}`} alt=""/>{data.champions[row.id].name}</h4>{row.reasons.map(text=><p key={text}>{text}</p>)}</article>)}</div><p className="hint">Sugestões de complementaridade, não estatísticas de duplas ou combos garantidos. Fontes de cura/escudo podem ser próprias; confirme o alvo permitido.</p></section></section>;
}
