'use client';
import {useState} from 'react';
import type {Dataset,Scenario,SkillKey} from './contracts';
import {plain,conservative} from './model';
import {skillUsage} from './contextGuide';
import {splashURL} from './skins';
import GuideText from './GuideText';
import GateKeepPro from './auth/GateKeepPro';
export default function GuideSkills({scenario:s,data}:{scenario:Scenario;data:Dataset}){
 const c=data.champions[s.player.champion];const [active,setActive]=useState(0),[failedArt,setFailedArt]=useState('');
 const sp=c.spells[active],key=(['Q','W','E','R'] as const)[active],usage=skillUsage(sp.description);
 const sequence=s.player.skills.length?s.player.skills:conservative(data,c.id);
 const priority=(['Q','W','E'] as SkillKey[]).sort((a,b)=>{const fifth=(key:SkillKey)=>sequence.map((v,i)=>v===key?i:-1).filter(i=>i>=0)[4]??99;return fifth(a)-fifth(b)||sequence.filter(v=>v===b).length-sequence.filter(v=>v===a).length;});
 const skins=[{num:0},...c.skins.filter(skin=>skin.num>0&&skin.parentSkin===undefined)];
 const art=splashURL(c.id,skins[active%skins.length]);
 return <section id="guide-skills"><div className="panel-head"><h3>Habilidades</h3><span className="hint">{sequence.length?priority.join(' → '):'Ordem especial pendente'} · caminho configurado</span></div><details className="guide-path"><summary>Ver caminho de níveis 1–18</summary><div className="skill-scroll"><table className="skill-table"><thead><tr><th>Nível</th>{Array.from({length:18},(_,i)=><th key={i}>{i+1}</th>)}</tr></thead><tbody><tr><th>Path</th>{Array.from({length:18},(_,i)=><td key={i}>{sequence[i]??'—'}</td>)}</tr></tbody></table></div><p className="hint">Ordem configurada no editor; não é estatística de meta.</p></details>
 <div className="guide-skill-tabs" role="tablist" aria-label="Escolher habilidade">{c.spells.map((spell,i)=><button key={spell.id} type="button" id={`skill-tab-${i}`} role="tab" aria-selected={active===i} aria-controls="guide-skill-panel" onClick={()=>setActive(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(i+(e.key==='ArrowRight'?1:3))%4;setActive(next);e.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('button')[next]?.focus();}}}><img src={`/assets/riot/icons/spell/${spell.image.full}`} alt=""/><kbd>{['Q','W','E','R'][i]}</kbd><span>{spell.name}</span></button>)}</div>
 <div className="guide-skill-panel" id="guide-skill-panel" role="tabpanel" aria-labelledby={`skill-tab-${active}`}><div className="guide-skill-copy"><h4>{key} · {sp.name}</h4><p><GuideText text={plain(sp.description)} data={data}/></p><p><strong>Quando usar:</strong> <GuideText text={usage.moment} data={data}/></p><details className="guide-more" key={`${c.id}:${key}`}><summary>Dicas de execução <span className="pro-small">PRO</span></summary><GateKeepPro><p><strong>Posicionamento:</strong> <GuideText text={usage.position} data={data}/></p><p><strong>Evite:</strong> <GuideText text={usage.mistake} data={data}/></p>{c.id==='Shen'&&<p><GuideText text={key==='Q'?'Prepare a posição da espada antes da troca. Aperto dos Mortos-Vivos depende de conseguir aplicar o ataque; a ativação não é garantida só por usar [[skill:Shen:Q]].':key==='E'?'Pós-Choque depende de acertar a imobilização de [[skill:Shen:E]]. Preserve uma saída quando o aliado não puder acompanhar.':key==='W'?'Reserve [[skill:Shen:W]] para ataques inimigos. Para comparar descrições de defesa, consulte também [[skill:Jax:E]]; os gatilhos são diferentes, sem equivalência automática de efeitos.':'Antes de [[skill:Shen:R]], avalie risco de interrupção e custo de abandonar sua rota.'} data={data}/></p>}</GateKeepPro></details><small className="hint">Orientação estimada pelo catálogo. Arte ilustrativa; a troca de skin não altera a habilidade.</small></div><div className="guide-skill-art"><img key={art} data-skill-art={key} src={failedArt===art?splashURL(c.id):art} alt={`Arte ilustrativa de ${c.name} para ${key}`} onError={()=>setFailedArt(art)}/><span>{c.name} <kbd>{key}</kbd></span></div></div></section>;
}
