'use client';
import {useMemo,useState} from 'react';
import type {Dataset,Scenario} from './contracts';
import {guideMatchups,guideAllies} from './contextGuide';
import GuideText from './GuideText';
import GateKeepPro from './auth/GateKeepPro';
export default function GuideMatchups({scenario:s,data}:{scenario:Scenario;data:Dataset}){
 const matchups=useMemo(()=>guideMatchups(s,data),[s.player.champion,s.player.lane,data]);
 const allies=useMemo(()=>guideAllies(s,data),[s.player.champion,s.player.lane,data]);
 const [selected,setSelected]=useState<{group:string;id:string}|null>(null);
 const groups=[{key:'hard',title:'Matchups difíceis',hint:'Mais pressão identificada pelo kit',rows:matchups.hard},{key:'best',title:'Matchups favoráveis',hint:'Possíveis vantagens pelas características',rows:matchups.best},{key:'allies',title:'Campeões que sinergizam',hint:'Complementaridade de funções',rows:allies}];
 const group=groups.find(g=>g.key===selected?.group),row=group?.rows.find(r=>r.id===selected?.id);
 return <section id="guide-matchups" className="guide-matchup-module"><div className="panel-head"><h3>Matchups e sinergias</h3><span className="testing-tag">Estimativa de Kit · sem win rate</span></div><div className="guide-matchup-groups">{groups.map(g=><section className={`guide-matchup-group ${g.key}`} key={g.key} id={g.key==='allies'?'guide-synergies':undefined}><h4>{g.title}</h4><p className="hint">{g.hint}</p><div className="guide-champion-strip">{g.rows.map(r=><button type="button" key={r.id} className="guide-champion-tile" aria-label={`${g.title}: ${data.champions[r.id].name}`} aria-pressed={selected?.group===g.key&&selected.id===r.id} onClick={()=>setSelected(selected?.group===g.key&&selected.id===r.id?null:{group:g.key,id:r.id})}><img src={`/assets/riot/icons/champion/${data.champions[r.id].image.full}`} alt=""/><strong>{data.champions[r.id].name}</strong><small>{g.key==='allies'?'Sinergia':'pressure' in r?`Pressão ${r.pressure}`:'Kit'}</small></button>)}</div>{!g.rows.length&&<p className="hint">Sem vantagem suficiente identificada. Não há lista de favoritos inventada.</p>}</section>)}</div>
 {row&&<div className="guide-matchup-detail"><div className="panel-head"><h4>{data.champions[row.id].name} · {group!.title}</h4><button type="button" aria-label="Fechar detalhes do campeão" onClick={()=>setSelected(null)}>×</button></div>{group!.key==='allies'?row.reasons.map(text=><p key={text}><GuideText text={text} data={data}/></p>):<GateKeepPro>{row.reasons.map(text=><p key={text}><GuideText text={text} data={data}/></p>)}</GateKeepPro>}</div>}
 <details className="guide-more"><summary>Como interpretar esta análise? <span className="pro-small">PRO</span></summary><GateKeepPro><p>Pressão: maior alcance básico +1; burst contra perfil sem tanque +2; CC duro +1; tanque contra seu burst +2; sua durabilidade contra burst −2; seu controle contra burst −1. Mobilidade, alcance de feitiços, itens e execução podem inverter a leitura.</p></GateKeepPro></details><p className="hint">Catálogo completo, sem filtro de popularidade por rota. São características do kit, não estatísticas locais/globais de partidas. Cura/escudo pode ser próprio; confirme o alvo permitido.</p></section>;
}
