'use client';
import {useId,useLayoutEffect,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {Coins,Info} from 'lucide-react';
import type {Dataset,Fighter} from './contracts';
import {parseItemHTML,type ItemText} from './itemTooltip';
import {plain} from './model';
const n=(v:number)=>v.toLocaleString('pt-BR');
function Text({parts}:{parts:ItemText[]}){return <>{parts.map((p,i)=>p.break?<br key={i}/>:<span key={i} className={`it-${p.tone} ${p.bold?'it-bold':''}`}>{p.text}</span>)}</>;}
export default function ItemTooltip({id,data,children,pinOnClick=false}:{id:string;f:Fighter;data:Dataset;context:string;children:ReactNode;pinOnClick?:boolean}){
 const [open,setOpen]=useState(false),[position,setPosition]=useState({left:0,top:0,caret:0,ready:false}),anchor=useRef<HTMLDivElement>(null),card=useRef<HTMLElement>(null),tooltipId=useId();
 const item=data.items[id];
 useLayoutEffect(()=>{if(!open)return;function locate(){const image=anchor.current?.querySelector('img'),a=(image??anchor.current)?.getBoundingClientRect(),c=card.current;if(!a||!c)return;const w=c.offsetWidth,center=a.left+a.width/2,left=Math.max(8,Math.min(center-w/2,window.innerWidth-w-8)),available=Math.max(0,a.top-18);c.style.maxHeight=`${available}px`;const h=c.offsetHeight;setPosition({left,top:a.top-h-10,caret:center-left,ready:true});}locate();const resize=new ResizeObserver(locate);if(card.current)resize.observe(card.current);window.addEventListener('resize',locate);window.addEventListener('scroll',locate,true);const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('keydown',esc);return()=>{resize.disconnect();window.removeEventListener('resize',locate);window.removeEventListener('scroll',locate,true);document.removeEventListener('keydown',esc);};},[open,id]);
 if(!item)return <>{children}</>;
 const stats=item.description.match(/<stats>([\s\S]*?)<\/stats>/i)?.[1]??'',body=item.description.replace(/<stats>[\s\S]*?<\/stats>/i,'').replace(/^<mainText>(?:<br>)+/i,'<mainText>');
 const show=()=>{setPosition(p=>({...p,ready:false}));setOpen(true);};
 return <div ref={anchor} className="item-tooltip-anchor" aria-describedby={open?tooltipId:undefined} onClick={()=>{if(pinOnClick){if(open)setOpen(false);else show();}}} onPointerEnter={e=>{if(e.pointerType!=='touch')show();}} onPointerLeave={()=>setOpen(false)} onFocusCapture={e=>{if(e.target instanceof HTMLElement&&e.target.matches(':focus-visible'))show();}} onBlurCapture={()=>setOpen(false)}>{children}<button type="button" className="item-info-pin" aria-label={`Detalhes de ${plain(item.name)}`} aria-expanded={open} onClick={e=>{e.stopPropagation();if(open)setOpen(false);else show();}}><Info size={15}/></button>{open&&createPortal(<aside id={tooltipId} ref={card} className="item-hover-card pointer-events-none" role="tooltip" aria-label={`Item: ${plain(item.name)}`} style={{left:position.left,top:position.top,visibility:position.ready?'visible':'hidden','--item-caret-left':`${position.caret}px`} as React.CSSProperties}><div className="item-tooltip-content"><header><img alt="" src={`/assets/riot/icons/item/${item.image.full}`}/><div><h3>{plain(item.name)}</h3><p><Coins size={13}/>{n(item.gold.total)} <span>ouro</span></p></div></header>{stats&&<div className="it-stat-list">{stats.split(/<br\s*\/?\s*>/i).filter(v=>plain(v)).map((html,i)=><div key={i}><Text parts={parseItemHTML(html)}/></div>)}</div>}<div className="it-description"><Text parts={parseItemHTML(body)}/></div></div><span className="item-tooltip-caret" aria-hidden="true"/></aside>,document.body)}</div>;
}
