'use client';
import {matchupRuneReason} from './runeOptimizer';
import WorkspaceNav from './WorkspaceNav';
import {useMemo,useState} from 'react';
import BuildControls from './BuildControls';
import ModelBadge from './ModelBadge';
import type {Dataset,Scenario} from './contracts';
import type {PatchState} from './patchService';
import PatchBadge from './PatchBadge';
import SessionBadge from './auth/SessionBadge';
import ShareBuildButton from './ShareBuildModal';
import ItemTooltip from './ItemTooltip';
import {quickRecommendation} from './quickRecommendation';
import {quickScenario} from './quickScenario';
import {fighter,plain} from './model';
import {PROFILE_LABELS} from './recommendation';
import {sequentialPurchases} from './fullBuild';
import {skillPlan} from './skillOrders';
import {splashURL} from './skins';
import ChampionPicker from './ChampionPicker';
import {ShardIcon} from './AttributeLabel';
import {SHARD_LABELS} from './shards';
const cdn='/assets/riot/icons/',lanes=['Top','Jungle','Mid','Bot','Support'],roles=['Topo','Selva','Meio','Atirador','Suporte'];
export default function QuickLab({data,scenario:s,onChange,onAdvanced,patchState,notification,onRetry,syncing}:{patchState:PatchState;notification:string;onRetry:()=>void;syncing:boolean;data:Dataset;scenario:Scenario;onChange:(s:Scenario)=>void;onAdvanced:()=>void;pro:boolean;canEditFormulas:boolean}){
 const [adjustments,setAdjustments]=useState<Partial<Scenario>>({});
 const auto=useMemo(()=>({...quickScenario(s,data),...adjustments}),[data,s.player.champion,s.player.lane,s.enemy.champion,s.matchupUnknown,adjustments]);
 const rec=useMemo(()=>quickRecommendation(auto,data),[auto,data]),plan=useMemo(()=>skillPlan(auto,data),[auto,data]);
 const c=data.champions[auto.player.champion],enemy=data.champions[auto.enemy.champion],preview={...auto,player:{...auto.player,items:rec.target,runes:rec.runes}};

 const choose=(side:'player'|'enemy',id:string)=>onChange(id==='unknown'?{...s,matchupUnknown:true,counterPreset:undefined}:{...s,[side]:{...fighter(data,id),lane:s[side].lane},...(side==='enemy'?{matchupUnknown:false}:{}),counterPreset:undefined});
 const item=(id:string,i:number)=><ItemTooltip key={id} id={id} f={preview.player} data={data} context={rec.reasons[id]??"Build automática por kit, rota e adversário"} pinOnClick><button className="fast-item" aria-label={`${i+1}. ${plain(data.items[id].name)}`}><span className="fast-order">{i+1}</span><img src={cdn+'item/'+data.items[id].image.full} alt=""/><strong>{plain(data.items[id].name)}</strong><small>{data.items[id].gold.total.toLocaleString('pt-BR')} G</small></button></ItemTooltip>;
 return <div className="quick-shell fast-shell"><header className="quick-header"><a className="quick-brand" href="#"><img src="/aegis-icon.png" width={28} height={28} alt=""/><span>AEGIS <b>LAB</b></span></a><PatchBadge state={patchState}/></header><WorkspaceNav mode="quick" onQuick={()=>window.scrollTo({top:0,behavior:'smooth'})} onManual={onAdvanced} sections={[{id:'fast-matchup',label:'Confronto'},{id:'fast-runes',label:'Runas'},{id:'fast-skills',label:'Habilidades'},{id:'fast-build',label:'Build'}]}/>
 <main className="quick-main fast-main"><SessionBadge/>{patchState.fallback&&<div className="catalog-status" role="status"><span>Usando catálogo local · você pode continuar.</span><button disabled={syncing} onClick={onRetry}>{syncing?'Sincronizando…':'Tentar sincronizar'}</button></div>}{notification&&<p className="notice" role="status">{notification}</p>}
 <section id="fast-matchup" className="fast-select" aria-label="Escolha seu confronto"><ChampionPicker data={data} value={c.id} label="Seu campeão" onChange={id=>choose('player',id)}/><label>Rota<select value={s.player.lane} onChange={e=>onChange({...s,player:{...s.player,lane:e.target.value},counterPreset:undefined})}>{lanes.map((lane,i)=><option key={lane} value={lane}>{roles[i]}</option>)}</select></label><ChampionPicker data={data} value={s.matchupUnknown?'unknown':enemy.id} label="Campeão inimigo" empty emptyValue="unknown" emptyLabel="Não sei ainda" onChange={id=>choose('enemy',id)}/></section>
 <section className="fast-summary" aria-live="polite"><img src={splashURL(c.id)} alt={c.name}/><div><span className="quick-eyebrow">BUILD AUTOMÁTICA · {roles[lanes.indexOf(s.player.lane)]}</span><h1>{c.name}{!s.matchupUnknown&&<small> contra {enemy.name}</small>}</h1><p>{PROFILE_LABELS[rec.profile]} · {s.matchupUnknown?'Recomendação padrão por kit e rota':'Adaptada ao adversário selecionado'}</p></div><ModelBadge/></section>
 <details className="fast-adjustments"><summary>Ajustar objetivos e preferências</summary><BuildControls scenario={auto} total={rec.total} remaining={sequentialPurchases(rec.target,auto,data).remaining} onChange={patch=>setAdjustments(current=>({...current,...patch}))} onCommit={()=>{}}/><div className="quick-objectives"><label>Objetivo de dano<select aria-label="Objetivo de dano" value={auto.objective} onChange={e=>setAdjustments(current=>({...current,objective:e.target.value as Scenario['objective']}))}><option value="burst">Burst · primeiros 3s</option><option value="dps">DPS continuado</option><option value="single">Maior dano por ação</option></select></label><label>Objetivo defensivo<select aria-label="Objetivo defensivo" value={auto.defensiveObjective} onChange={e=>setAdjustments(current=>({...current,defensiveObjective:e.target.value as Scenario['defensiveObjective']}))}><option value="combo">Resistir ao combo</option><option value="survive">Sobreviver à janela</option><option value="sustain">Sustentar trocas</option></select></label><button onClick={()=>setAdjustments({})}>Restaurar perfil automático</button></div><p className="hint">Ajustes deste cartão. Inventário e travas do Laboratório permanecem preservados. A mesma build pode continuar adequada após mudar o objetivo.</p></details>
 <section className="fast-layout"><section id="fast-runes" className="fast-panel fast-runes"><h2>Runas recomendadas</h2><div className="fast-rune-trees">{[rec.runes.primary,rec.runes.secondary].map((id,n)=>{const tree=data.runes.find(t=>t.id===id)!;return <div key={id}><h3>{tree.name}<small>{n===0?'Principal':'Secundária'}</small></h3>{tree.slots.map((slot,i)=><div className="fast-rune-row" key={i}>{slot.runes.map(r=><button key={r.id} className={rec.runes.selected.includes(r.id)?'selected':''} title={`${r.name}: ${plain(r.longDesc||r.shortDesc)}`} aria-label={`${r.name}${rec.runes.selected.includes(r.id)?' · recomendada':''}`} aria-pressed={rec.runes.selected.includes(r.id)}><img src={cdn+r.icon} alt=""/></button>)}</div>)}</div>;})}</div><div className="fast-shards">{rec.runes.shards.map((shard,i)=><span key={i} title={['Ofensivo','Flexível','Defensivo'][i]}><ShardIcon shard={shard}/><span>{SHARD_LABELS[shard]??shard}</span></span>)}</div><p className="hint">Passe o mouse ou foque uma runa para ler a descrição.</p><details className="fast-skill-reason"><summary>Por que estas runas neste confronto?</summary><p>{matchupRuneReason(auto,data,rec.runes)}</p><small>Kit e rota + respostas contextuais estimadas. Uma troca de inimigo pode manter escolhas que continuam adequadas.</small></details></section>
 <section id="fast-skills" className="fast-panel fast-skills"><h2>Habilidades</h2><small>Prioridade de maximização</small><div className="fast-priority">{plan.priority.map((key,i)=>{const spell=c.spells[['Q','W','E','R'].indexOf(key)];return <span key={key}>{i>0&&<b>›</b>}<span title={`${key} · ${plain(spell.name)}`}><img src={cdn+'spell/'+spell.image.full} alt={plain(spell.name)}/><em>{key}</em></span></span>;})}</div><small>Primeiros níveis</small><div className="fast-opening">{plan.sequence.slice(0,6).map((key,i)=><span key={i}><small>{i+1}</small><b>{key}</b></span>)}</div><div className="hint" title={plan.reason}>{plan.coverage==='observed'?'Sequência observada na rota':'Sequência estimada'} · <details className="fast-skill-reason"><summary>Por que esta sequência?</summary><p>{plan.reason}</p></details></div></section>
 <section id="fast-build" className="fast-panel fast-build"><div className="fast-build-head"><h2>Ordem de compra</h2><small>{rec.total.toLocaleString('pt-BR')} G · build completa</small></div><div className="fast-items">{rec.target.map(item)}</div><p className="hint">{roles[lanes.indexOf(s.player.lane)]} · {s.matchupUnknown?'Sem counter definido':`Resposta ao kit de ${enemy.name}`}. Passe o mouse, foque ou toque no ícone de informação para ver os detalhes.</p></section></section>
 <div className="fast-bottom"><p>Escolha o confronto e receba a sugestão. Ajuste objetivos neste cartão. Inventário, travas e simulação ficam no Laboratório Manual.</p><button className="primary" onClick={onAdvanced}>Abrir Laboratório Manual</button><ShareBuildButton scenario={preview} data={data}/></div>
 <details className="fast-coverage"><summary>Como esta recomendação é calculada?</summary><p>Perfil automático por classe e rota. Kits incompletos: o ranking usa um índice de atributos e sinergias, separado do DPS estimado por classe. DPS exato indisponível até validar fórmulas, passivas e condições do kit. Não é uma garantia de build ótima nem uma estatística de vitória. Sliders, inventário e travas do Manual não alteram este cartão.</p>{rec.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>
 </main></div>;
}
