'use client';
import WorkspaceNav from './WorkspaceNav';
import {useMemo} from 'react';
import type {Dataset,Scenario} from './contracts';
import type {PatchState} from './patchService';
import PatchBadge from './PatchBadge';
import SessionBadge from './auth/SessionBadge';
import ShareBuildButton from './ShareBuildModal';
import ItemTooltip from './ItemTooltip';
import {quickRecommendation} from './quickRecommendation';
import {quickScenario} from './quickScenario';
import {fighter,plain} from './model';
import {PROFILE_LABELS} from './recommendation';
import {skillPlan} from './skillOrders';
import {splashURL} from './skins';
import {SHARD_LABELS} from './shards';
const cdn='/assets/riot/icons/',lanes=['Top','Jungle','Mid','Bot','Support'],roles=['Topo','Selva','Meio','Atirador','Suporte'];
export default function QuickLab({data,scenario:s,onChange,onAdvanced,patchState,notification}:{patchState:PatchState;notification:string;data:Dataset;scenario:Scenario;onChange:(s:Scenario)=>void;onAdvanced:()=>void;pro:boolean;canEditFormulas:boolean}){
 const auto=useMemo(()=>quickScenario(s,data),[data,s.player.champion,s.player.lane,s.enemy.champion,s.matchupUnknown]);
 const rec=useMemo(()=>quickRecommendation(auto,data),[auto,data]),plan=useMemo(()=>skillPlan(auto,data),[auto,data]);
 const c=data.champions[auto.player.champion],enemy=data.champions[auto.enemy.champion],preview={...auto,player:{...auto.player,items:rec.target,runes:rec.runes}};
 const champions=Object.values(data.champions).sort((a,b)=>a.name.localeCompare(b.name));
 const choose=(side:'player'|'enemy',id:string)=>onChange(id==='unknown'?{...s,matchupUnknown:true,counterPreset:undefined}:{...s,[side]:{...fighter(data,id),lane:s[side].lane},...(side==='enemy'?{matchupUnknown:false}:{}),counterPreset:undefined});
 const item=(id:string,i:number)=><ItemTooltip key={id} id={id} f={preview.player} data={data} context={rec.reasons[id]??"Build automática por kit, rota e adversário"} pinOnClick><button className="fast-item" aria-label={`${i+1}. ${plain(data.items[id].name)}`}><span className="fast-order">{i+1}</span><img src={cdn+'item/'+data.items[id].image.full} alt=""/><strong>{plain(data.items[id].name)}</strong><small>{id===rec.boots?'Bota':i<3?'Principal':'Complemento'}</small></button></ItemTooltip>;
 return <div className="quick-shell fast-shell"><header className="quick-header"><a className="quick-brand" href="#"><img src="/aegis-icon.png" width={28} height={28} alt=""/><span>AEGIS <b>LAB</b></span></a><PatchBadge state={patchState}/></header><WorkspaceNav mode="quick" onQuick={()=>window.scrollTo({top:0,behavior:'smooth'})} onManual={onAdvanced} sections={[{id:'fast-matchup',label:'Confronto'},{id:'fast-runes',label:'Runas'},{id:'fast-skills',label:'Habilidades'},{id:'fast-build',label:'Build'}]}/>
 <main className="quick-main fast-main"><SessionBadge/>{notification&&<p className="notice" role="status">{notification}</p>}
 <section id="fast-matchup" className="fast-select" aria-label="Escolha seu confronto"><label>Seu campeão<select value={c.id} onChange={e=>choose('player',e.target.value)}>{champions.map(ch=><option key={ch.id} value={ch.id}>{ch.name}</option>)}</select></label><label>Rota<select value={s.player.lane} onChange={e=>onChange({...s,player:{...s.player,lane:e.target.value},counterPreset:undefined})}>{lanes.map((lane,i)=><option key={lane} value={lane}>{roles[i]}</option>)}</select></label><label>Campeão inimigo<select value={s.matchupUnknown?'unknown':enemy.id} onChange={e=>choose('enemy',e.target.value)}><option value="unknown">Não sei ainda</option>{champions.map(ch=><option key={ch.id} value={ch.id}>{ch.name}</option>)}</select></label></section>
 <section className="fast-summary" aria-live="polite"><img src={splashURL(c.id)} alt={c.name}/><div><span className="quick-eyebrow">BUILD AUTOMÁTICA · {roles[lanes.indexOf(s.player.lane)]}</span><h1>{c.name}{!s.matchupUnknown&&<small> contra {enemy.name}</small>}</h1><p>{PROFILE_LABELS[rec.profile]} · {s.matchupUnknown?'Recomendação padrão por kit e rota':'Adaptada ao adversário selecionado'}</p></div><span className="testing-tag">Estimativa de kit</span></section>
 <section className="fast-layout"><section id="fast-runes" className="fast-panel fast-runes"><h2>Runas recomendadas</h2><div className="fast-rune-trees">{[rec.runes.primary,rec.runes.secondary].map((id,n)=>{const tree=data.runes.find(t=>t.id===id)!;return <div key={id}><h3>{tree.name}<small>{n===0?'Principal':'Secundária'}</small></h3>{tree.slots.map((slot,i)=><div className="fast-rune-row" key={i}>{slot.runes.map(r=><button key={r.id} className={rec.runes.selected.includes(r.id)?'selected':''} title={`${r.name}: ${plain(r.longDesc||r.shortDesc)}`} aria-label={`${r.name}${rec.runes.selected.includes(r.id)?' · recomendada':''}`} aria-pressed={rec.runes.selected.includes(r.id)}><img src={cdn+r.icon} alt=""/></button>)}</div>)}</div>;})}</div><div className="fast-shards">{rec.runes.shards.map((shard,i)=><span key={i} title={['Ofensivo','Flexível','Defensivo'][i]}>{SHARD_LABELS[shard]??shard}</span>)}</div><p className="hint">Passe o mouse ou foque uma runa para ler a descrição.</p></section>
 <section id="fast-skills" className="fast-panel fast-skills"><h2>Habilidades</h2><small>Prioridade de maximização</small><div className="fast-priority">{plan.priority.map((key,i)=>{const spell=c.spells[['Q','W','E','R'].indexOf(key)];return <span key={key}>{i>0&&<b>›</b>}<span title={`${key} · ${plain(spell.name)}`}><img src={cdn+'spell/'+spell.image.full} alt={plain(spell.name)}/><em>{key}</em></span></span>;})}</div><small>Primeiros níveis</small><div className="fast-opening">{plan.sequence.slice(0,6).map((key,i)=><span key={i}><small>{i+1}</small><b>{key}</b></span>)}</div><div className="hint" title={plan.reason}>{plan.coverage==='observed'?'Sequência observada na rota':'Sequência estimada'} · <details className="fast-skill-reason"><summary>Por que esta sequência?</summary><p>{plan.reason}</p></details></div></section>
 <section id="fast-build" className="fast-panel fast-build"><div className="fast-build-head"><h2>Ordem de compra</h2><small>{rec.total.toLocaleString('pt-BR')} G · build completa</small></div><div className="fast-items">{rec.target.map(item)}</div><p className="hint">{roles[lanes.indexOf(s.player.lane)]} · {s.matchupUnknown?'Sem counter definido':`Resposta ao kit de ${enemy.name}`}. Clique em um item para ver atributos e descrição.</p></section></section>
 <div className="fast-bottom"><p>Escolha o confronto e receba a sugestão. Ajustes de atributos, orçamento, itens e simulação ficam no Laboratório Manual.</p><button className="primary" onClick={onAdvanced}>Abrir Laboratório Manual</button><ShareBuildButton scenario={preview} data={data}/></div>
 <details className="fast-coverage"><summary>Como esta recomendação é calculada?</summary><p>Perfil automático por classe e rota; atributos e respostas ao kit adversário são estimados. Não é uma garantia de build ótima nem uma estatística de vitória. Sliders, inventário e travas do Manual não alteram este cartão.</p>{rec.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>
 </main></div>;
}
