'use client';
import PresetPanel from './PresetPanel';
import ShareBuildButton from './ShareBuildModal';
import ProModal from './auth/ProModal';
import {useAuth} from './auth/AuthProvider';
import MatchupComparator from './MatchupComparator';
import SessionBadge from './auth/SessionBadge';
import ContextAssistant from './ContextAssistant';
import {useMemo,useState,useRef} from 'react';
import {Shield,ArrowLeft,ArrowRight,Swords,ChevronDown,Copy,Check,FlaskConical,SlidersHorizontal,Coins,Lock,TrendingUp,HeartPulse,Layers,Info} from 'lucide-react';
import type {Dataset,Scenario,Fighter} from './contracts';
import {fighter,statsFor,itemEligible,plain} from './model';
import {recommend,goldCheck,quickCombat,itemSetJSON,PROFILE_LABELS,type TacticalMode} from './recommendation';
import {splashURL} from './skins';
import {Modal,NumberInput,RuneEditor} from './components';
import AbilityTooltip from './AbilityTooltip';
import StackPanel from './StackPanel';
import ItemTooltip from './ItemTooltip';
import BuildControls from './BuildControls';
import type {PatchState} from './patchService';
import PatchBadge from './PatchBadge';
import {fullBuild,sequentialPurchases} from './fullBuild';
import {itemCategories} from './stacks';
const cdn='/assets/riot',num=(n:number)=>Number.isFinite(n)?n.toLocaleString('pt-BR',{maximumFractionDigits:1}):'—';
const modes:{id:TacticalMode;label:string}[]=[{id:'behind',label:'Estou atrás'},{id:'snowball',label:'Snowball'},{id:'antiheal',label:'Anti-cura'},{id:'antishield',label:'Anti-shield'}];
const categories=[['all','Todos'],['mana','Mana / Lágrima'],['physical','Dano físico'],['ap','Poder de habilidade'],['defense','Defesa / Tanques'],['support','Utilidade / Suporte']];
export default function QuickLab({data,scenario:s,onChange,onAdvanced,pro,canEditFormulas,patchState,notification}:{patchState:PatchState;notification:string;data:Dataset;scenario:Scenario;onChange:(s:Scenario)=>void;onAdvanced:()=>void;pro:boolean;canEditFormulas:boolean}){
 const {isPro:authPro}=useAuth();
 const [mode,setMode]=useState<TacticalMode>('balanced'),[skinNum,setSkinNum]=useState(0),[showBuild,setShowBuild]=useState(false),[showPro,setShowPro]=useState(false),[toast,setToast]=useState(''),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[editSide,setEditSide]=useState<'player'|'enemy'>('player');
 const c=data.champions[s.player.champion],enemy=data.champions[s.enemy.champion];
 const latest=useRef(s);latest.current=s;
 const previousTarget=useRef<string[]>([]);
 const context=JSON.stringify({...s,budget:null});
 const rec=useMemo(()=>{const r=fullBuild(s,data,mode,previousTarget.current);previousTarget.current=r.target;return r;},[data,mode,context]);
 const commitPreference=()=>{};
 const preview=useMemo(()=>({...s,player:{...s.player,items:rec.target,runes:rec.runes}}),[s,rec]);
 const calculations=useMemo(()=>{if(s.matchupUnknown)return {result:null,error:''};try{return {result:quickCombat(preview,data,rec.target),error:''};}catch(e){return {result:null,error:e instanceof Error?e.message:String(e)};}},[preview,data,rec]);
 const purchase=useMemo(()=>{try{return {result:sequentialPurchases(rec.target,s,data),error:''};}catch(e){return {result:null,error:e instanceof Error?e.message:String(e)};}},[s,data,rec]);
 const st=statsFor(preview.player,data),combat=calculations.result,p= purchase.result;
 const update=(patch:Partial<Scenario>)=>onChange({...s,...patch});
 const setF=(side:'player'|'enemy',patch:Partial<Fighter>)=>onChange({...s,[side]:{...s[side],...patch}});
 const choose=(side:'player'|'enemy',id:string)=>{if(side==='enemy'&&id==='unknown'){update({matchupUnknown:true,counterPreset:undefined});return;}const next=fighter(data,id);next.lane=s[side].lane;onChange({...s,...(side==='enemy'?{matchupUnknown:false,counterPreset:undefined}:{}),[side]:next});if(side==='player')setSkinNum(0);setToast('');};
 const eligible=Object.entries(data.items).filter(([id,i])=>itemEligible(id,data,s[editSide].champion)&&(category==='all'||itemCategories(id,data).includes(category))&&(plain(i.name).toLowerCase().includes(search.toLowerCase())||id===search)).sort((a,b)=>a[1].gold.total-b[1].gold.total||a[1].name.localeCompare(b[1].name));
 async function copyItems(){if(!authPro){setShowPro(true);return;}const text=itemSetJSON(c.id,data,rec.cores,rec.boots,p?.steps.filter(x=>x.available&&!x.owned).map(x=>x.id)??[]);try{await navigator.clipboard.writeText(text);setToast('JSON copiado. No cliente: Coleção → Itens → Importar conjunto de itens.');}catch{const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`aegis-${c.id}-itens.json`;a.click();URL.revokeObjectURL(url);setToast('JSON exportado; importe-o em Coleção → Itens no cliente.');}}
 const itemTile=(id:string,index:number,boot=false)=><ItemTooltip id={id} f={preview.player} data={data} context="Build recomendada completa" pinOnClick key={id}><button className={`quick-item ${boot?'quick-boot':''} ${p?.steps[index]?.available?'purchasable':'planned'}`} key={id} onClick={()=>{}}><div className="quick-item-image"><img src={`${cdn}/icons/item/${data.items[id].image.full}`} alt="" onError={e=>{e.currentTarget.style.opacity='.15';}}/></div><strong>{plain(data.items[id].name)}</strong><small>{num(data.items[id].gold.total)} G</small><span className="item-number">{String(index+1).padStart(2,'0')}</span><span className="item-purchase-state">{p?.steps[index]?.owned?'Já possuído':p?.steps[index]?.available?'Disponível para compra':'Meta futura'}</span><small>Conclusão: {num(p?.steps[index]?.cost??data.items[id].gold.total)} G{p?.steps[index]?.credit?` · crédito ${num(p.steps[index].credit)} G`:""}</small><span className="quick-item-note" title={boot?'Mobilidade para o confronto':rec.reasons[id]}>{boot?'Mobilidade para o confronto':rec.reasons[id]}</span></button></ItemTooltip>;
 return <div className="quick-shell"><header className="quick-header"><a className="quick-brand" href="#" onClick={e=>e.preventDefault()}><img src="/aegis-icon.png" width={32} height={32} alt=""/><span>AEGIS <b>LAB</b></span></a><nav><span className="quick-active">Cartão rápido</span><button onClick={onAdvanced}>Editor manual</button></nav><PatchBadge state={patchState}/></header>
 <main className="quick-main"><SessionBadge/>{notification&&<p className="notice" role="status">{notification}</p>}<section className="quick-selection"><label><span>Seu campeão</span><select value={c.id} onChange={e=>choose('player',e.target.value)}>{Object.values(data.champions).sort((a,b)=>a.name.localeCompare(b.name)).map(ch=><option key={ch.id} value={ch.id}>{ch.name}</option>)}</select></label><label><span>Nível</span><input aria-label="Seu nível" type="number" min={1} max={18} value={s.player.level} onChange={e=>setF('player',{level:Math.max(1,Math.min(18,Math.round(Number(e.target.value))))})}/></label><div className="quick-vs">VS</div><label><span>Adversário</span><select value={s.matchupUnknown?'unknown':enemy.id} onChange={e=>choose('enemy',e.target.value)}><option value="unknown">Não sei ainda · build padrão</option>{Object.values(data.champions).sort((a,b)=>a.name.localeCompare(b.name)).map(ch=><option key={ch.id} value={ch.id}>{ch.name}</option>)}</select></label><label><span>Nível</span><input aria-label="Nível do adversário" disabled={s.matchupUnknown} type="number" min={1} max={18} value={s.enemy.level} onChange={e=>setF('enemy',{level:Math.max(1,Math.min(18,Math.round(Number(e.target.value))))})}/></label><label><span>Rota</span><select value={s.player.lane} onChange={e=>setF('player',{lane:e.target.value})}>{['Top','Jungle','Mid','Bot','Support'].map(l=><option key={l}>{l}</option>)}</select></label>{c.tags.includes('Support')&&<label><span>Perfil de suporte</span><select value={s.player.supportMode??'auto'} onChange={e=>setF('player',{supportMode:e.target.value as Fighter['supportMode']})}><option value="auto">Automático pela rota</option><option value="utility">Utilidade</option><option value="damage">Dano</option></select></label>}</section>
 <section className="quick-card"><div className="quick-art"><img src={splashURL(c.id,c.skins.find(sk=>sk.num===skinNum))} alt={`Splash da skin base de ${c.name}`} onError={e=>{const fallback=splashURL(c.id,{num:0});if(e.currentTarget.src!==fallback)e.currentTarget.src=fallback;else e.currentTarget.style.opacity='0';}}/></div><div className="quick-card-head"><div><span className="quick-eyebrow">SEU PLANO PARA O CONFRONTO</span><h1>{c.name}<span>{s.matchupUnknown?' · Build padrão':` contra ${enemy.name}`}</span></h1><p>{PROFILE_LABELS[rec.profile]} · {s.player.lane}</p></div><span className="quick-coverage"><Info size={13}/>Sugestão exploratória</span></div>
 <div className="quick-card-body"><BuildControls scenario={s} total={rec.total} remaining={p?.remaining??s.budget} onChange={update} onCommit={commitPreference}/><div className="quick-build-heading"><h2>Build recomendada</h2></div><div className="quick-items">{rec.target.map((id,i)=>itemTile(id,i,id===rec.boots))}</div>
 <div className="quick-bottom-grid"><section className="quick-runes"><h3>Runas para este perfil</h3><RuneEditor page={rec.runes} f={preview.player} data={data} scenario={preview} update={runes=>setF('player',{runes})}/><small className="quick-muted">Scores de afinidade estimados por kit e slider. Apenas efeitos modelados entram nos cálculos.</small></section><section className="quick-verdict"><span className="quick-eyebrow"><FlaskConical size={14}/>VEREDICTO DO LABORATÓRIO</span><p>{rec.verdict}</p><AbilityTooltip f={preview.player} data={data} canEdit={canEditFormulas}/></section></div>
 {!s.matchupUnknown&&<div className="quick-impact" aria-live="polite"><div><Swords size={19}/><span><small>Dano modelado · {s.duration}s</small><b>{combat?num(combat.player.damage):'Indisponível'}</b><em>{s.player.actions.length?'Sequência configurada':'Ataques básicos · sem combo presumido'}</em></span></div><div><HeartPulse size={19}/><span><small>Sobrevivência na janela</small><b>{combat?combat.player.death===null?'Sobreviveu':`${num(combat.player.death)}s até morrer`:'Indisponível'}</b><em>{combat?`${num(combat.player.hp)} HP restantes`:'Ver cobertura'}</em></span></div><div><TrendingUp size={19}/><span><small>Primeiro marco de compra</small><b>{rec.cores[0]?`${num(data.items[rec.cores[0]].gold.total)} G`:'Sem core'}</b><em>Marco por ouro · minutos não estimados</em></span></div></div>}</div></section>
 {!s.matchupUnknown&&<details className="quick-context"><summary>Respostas ao matchup e draft</summary><ContextAssistant scenario={s} data={data} onChange={onChange}/></details>}<section className="quick-adapt"><div><h3>Como está a partida?</h3><span>Adapte o plano em um clique.</span></div><div className="quick-mode-buttons">{modes.map(m=><button key={m.id} aria-pressed={mode===m.id} className={mode===m.id?'selected':''} onClick={()=>setMode(mode===m.id?'balanced':m.id)}>{m.label}</button>)}</div></section>
 <div className="quick-tools-grid"><section className="quick-gold"><div className="quick-section-heading"><div><span className="quick-eyebrow">COMPRAS NA BASE</span><h2>Próximas compras</h2></div><Coins size={24}/></div><div className="quick-gold-input"><button onClick={()=>{setEditSide('player');setShowBuild(true);}}>Itens já possuídos <Layers size={16}/></button></div><div className="quick-purchase">{p?.steps.some(x=>x.available&&!x.owned)?p.steps.filter(x=>x.available&&!x.owned).map(({id})=><ItemTooltip key={id} id={id} f={s.player} data={data} context="Itens equipados agora" pinOnClick><button onClick={()=>{}}><img src={`${cdn}/icons/item/${data.items[id].image.full}`} alt=""/><span>{plain(data.items[id].name)}</span></button></ItemTooltip>):<p>Guarde o ouro para o próximo item da ordem. A meta completa continua visível.</p>}</div><p className="quick-muted">Compras na ordem estrita da build. Componentes possuídos descontados uma única vez; o primeiro item sem saldo bloqueia novas compras posteriores.</p>{p&&p.steps.some(x=>x.available&&!x.owned)&&<button className="quick-apply" onClick={()=>{const inventory=[...s.player.owned];for(const step of p.steps.filter(x=>x.available&&!x.owned)){for(const id of step.consumed){const n=inventory.indexOf(id);if(n>=0)inventory.splice(n,1);}inventory.push(step.id);}if(inventory.length>6){setToast('Inventário cheio: libere espaço antes de registrar.');return;}onChange({...s,budget:p.remaining,player:{...s.player,items:inventory,owned:inventory,locked:s.player.locked.filter(id=>inventory.includes(id))}});setToast('Compra registrada. Ouro disponível atualizado para o saldo restante.');}}>Registrar essa compra</button>}</section>
 <section className="quick-preferences"><span className="quick-eyebrow">PERSONALIZAÇÃO</span><h2>Preferências</h2><div className="quick-secondary-fields"><label>Skin base<select value={skinNum} onChange={e=>setSkinNum(Number(e.target.value))}>{c.skins.map(sk=><option key={sk.num} value={sk.num}>{sk.num===0?'Original':sk.name}</option>)}</select></label></div><button disabled={s.matchupUnknown} className="quick-enemy-edit" onClick={()=>{setEditSide('enemy');setShowBuild(true);}}>Editar build do adversário</button><details><summary>Acúmulos da build alvo</summary><StackPanel f={preview.player} data={data} onChange={stacks=>setF('player',{stacks})}/><p className="quick-muted">HP {num(st.hp)} · AP {num(st.ap)} · AS {num(st.as)} · AH básica {num(st.basicHaste??0)} · AH ultimate {num(st.ultimateHaste??0)}</p></details></section></div>
 {!s.matchupUnknown&&<MatchupComparator scenario={preview} data={data}/>} <PresetPanel scenario={preview} data={data} onLoad={onChange}/><section className="quick-milestones"><div className="quick-section-heading"><h3>Marcos de poder por compra</h3><span>Não é previsão de minutos</span></div><div>{rec.target.map((id,i)=><article key={id}><img className="item-inline-icon" src={`${cdn}/icons/item/${data.items[id].image.full}`} alt=""/><span>0{i+1}</span><strong>{plain(data.items[id].name)}</strong><small>{num(rec.target.slice(0,i+1).reduce((sum,key)=>sum+data.items[key].gold.total,0))} G na meta</small></article>)}</div></section>
 <footer className="quick-footer"><ShareBuildButton scenario={preview} data={data}/><button className="quick-export" onClick={copyItems}><Copy size={16}/>Copiar bloco de itens para o LoL (JSON)</button><button className="quick-pro" onClick={()=>pro?onAdvanced():setShowPro(true)}>Ver análise aprofundada <span>PRO</span><Lock size={14}/></button></footer>{toast&&<p className="quick-toast" role="status">{toast}</p>}{(calculations.error||purchase.error)&&<p role="alert" className="notice error">{calculations.error||purchase.error}</p>}
 <details className="quick-disclosure"><summary>O que este cartão calcula?</summary>{rec.warnings.map((w,i)=><p key={i}>{w}</p>)}{combat?.warnings.map((w,i)=><p key={'w'+i}>{w}</p>)}<p>A ordem sugerida não prova o maior pico relativo ao inimigo. Efeitos sem fórmula não recebem números. JSON no formato de conjunto de itens; importação no cliente não testada nesta entrega.</p></details></main>
 {showBuild&&<Modal title={editSide==='player'?'Itens já possuídos':'Build do adversário'} close={()=>setShowBuild(false)}><div className="quick-store-tabs">{categories.map(([id,label])=><button key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div><input aria-label="Buscar na loja" placeholder="Nome ou ID do item" value={search} onChange={e=>setSearch(e.target.value)}/><p className="hint">Preço crescente · {s[editSide].items.length} / 6 slots</p><div className="quick-owned-list">{s[editSide].items.map(id=><div key={id}><ItemTooltip id={id} f={s[editSide]} data={data} context="Itens equipados agora"><span className="item-inline"><img className="item-inline-icon" src={`${cdn}/icons/item/${data.items[id].image.full}`} alt=""/>{plain(data.items[id].name)}</span></ItemTooltip>{editSide==='player'&&<button aria-label={`Destravar ${plain(data.items[id].name)}`} onClick={()=>setF('player',{locked:s.player.locked.includes(id)?s.player.locked.filter(x=>x!==id):[...s.player.locked,id]})}>{s.player.locked.includes(id)?'Travado':'Livre'}</button>}<button disabled={s[editSide].locked.includes(id)} aria-label={`Remover ${plain(data.items[id].name)}`} onClick={()=>setF(editSide,{items:s[editSide].items.filter(x=>x!==id),owned:s[editSide].owned.filter(x=>x!==id)})}>Remover</button></div>)}</div><div className="item-catalog">{eligible.map(([id,item])=><ItemTooltip key={id} id={id} f={s[editSide]} data={data} context="Itens equipados agora"><button className="catalog-item" disabled={s[editSide].items.includes(id)||s[editSide].items.length>=s.slots} onClick={()=>{const f=s[editSide];if(item.tags.includes('Boots')&&f.items.some(x=>data.items[x].tags.includes('Boots'))){setToast('Somente um par de botas.');return;}setF(editSide,{items:[...f.items,id],owned:editSide==='player'?[...f.owned,id]:f.owned,locked:editSide==='player'?[...f.locked,id]:f.locked});}}><img src={`${cdn}/icons/item/${item.image.full}`} alt=""/><span><b>{plain(item.name)}</b><small>{num(item.gold.total)} G</small></span></button></ItemTooltip>)}</div></Modal>}

 {showPro&&<ProModal close={()=>setShowPro(false)}/>}
 </div>;
}
