'use client';
import {useState,type CSSProperties} from 'react';
import {Lock,Unlock,Swords,Zap,Heart,Footprints,Shield} from 'lucide-react';
import type {Dataset,RunePage,Rune,Scenario} from './contracts';
import {calculateOptimalRunes} from './runeOptimizer';
import {runeCompatible} from './compatibility';
import {selectManualRune,switchRuneTree,selectManualShard} from './runeSelection';
import {SHARD_ROWS,SHARD_LABELS} from './shards';
import {plain} from './model';
export interface RuneSelectorProps {page:RunePage;data:Dataset;scenario:Scenario;onChange:(page:RunePage)=>void}
const colors:Record<number,string>={8000:'#deb65d',8100:'#e36a75',8200:'#88b8ef',8400:'#82c77b',8300:'#8fd9d8'};
const cdn='https://ddragon.leagueoflegends.com/cdn/img/';
const shardIcons={adaptive:Swords,as:Zap,haste:Zap,move:Footprints,scalingHP:Heart,hp:Heart,tenacity:Shield};
export default function RuneSelector({page,data,scenario,onChange}:RuneSelectorProps){
 const [error,setError]=useState('');
 const primary=data.runes.find(t=>t.id===page.primary),secondary=data.runes.find(t=>t.id===page.secondary);
 function commit(next:RunePage){try{const resolved=calculateOptimalRunes({...scenario,player:{...scenario.player,runes:next}},data);onChange(resolved);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}
 function runeButton(r:Rune,tree:number,keystone=false){
  const selected=page.selected.includes(r.id),locked=page.locked||!!page.locks?.runes?.includes(r.id),compatibility=runeCompatible(r.id,scenario.player,data);
  return <span className="rs-slot" key={r.id}><button type="button" className={`rs-icon ${keystone?'rs-keystone':''} ${selected?'is-selected':''}`} style={{'--rune-color':colors[tree]??'#b5c5dc'} as CSSProperties} disabled={!compatibility.allowed&&!selected} aria-label={`${r.name}${locked?' · escolha travada':''}`} aria-pressed={selected} title={`${r.name}\n${plain(r.longDesc||r.shortDesc)}${!compatibility.allowed?'\nIncompatível com o kit deste campeão.':''}`} onClick={()=>{if(!selected||!locked)commit(selectManualRune(page,data,r.id));}}>
   <img src={cdn+r.icon} alt=""/>
  </button>{selected&&<button type="button" className="rs-lock-toggle" aria-label={`${locked?'Destravar':'Travar'} ${r.name}`} aria-pressed={locked} title={locked?'Clique para destravar e calcular automaticamente':'Clique para travar esta runa'} onClick={()=>commit(selectManualRune(page,data,r.id))}>{locked?<Lock size={13}/>:<Unlock size={13}/>}</button>}</span>;
 }
 return <section className="rune-selector" aria-label="Seleção de runas"><div className="rs-toolbar"><span>Escolha suas runas</span></div>
 <div className="rs-tabs" role="group" aria-label="Árvore primária">{data.runes.map(t=><span className="rs-slot" key={t.id}><button type="button" className={t.id===page.primary?'is-selected':''} style={{'--rune-color':colors[t.id]} as CSSProperties} aria-label={`Árvore primária: ${t.name}`} aria-pressed={t.id===page.primary} title={t.name} onClick={()=>commit(switchRuneTree(page,data,t.id,'primary'))}><img src={cdn+t.icon} alt=""/></button>{t.id===page.primary&&<button type="button" className="rs-lock-toggle" aria-label="Alternar trava da árvore primária" aria-pressed={!!page.locks?.primaryTree} title="Travar ou destravar árvore primária" onClick={()=>commit({...page,locked:false,locks:{...page.locks,primaryTree:!page.locks?.primaryTree}})}>{page.locks?.primaryTree?<Lock size={13}/>:<Unlock size={13}/>}</button>}</span>)}</div>
 <div className="rs-columns"><div className="rs-primary" style={{'--rune-color':colors[page.primary]} as CSSProperties}><header><img src={primary?cdn+primary.icon:undefined} alt=""/><h4>{primary?.name}</h4><small>Primária</small></header>{primary?.slots.map((row,i)=><div className="rs-row" key={i} role="group" aria-label={i===0?'Runas essenciais':`Linha primária ${i}`}>{row.runes.map(r=>runeButton(r,page.primary,i===0))}</div>)}</div>
 <div className="rs-secondary" style={{'--rune-color':colors[page.secondary]} as CSSProperties}><header><img src={secondary?cdn+secondary.icon:undefined} alt=""/><label><span className="sr-only">Árvore secundária</span><select aria-label="Árvore secundária" value={page.secondary} onChange={e=>commit(switchRuneTree(page,data,Number(e.target.value),'secondary'))}>{data.runes.filter(t=>t.id!==page.primary).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button type="button" className="rs-tree-lock" aria-label="Alternar trava da árvore secundária" aria-pressed={!!page.locks?.secondaryTree} title="Travar ou destravar árvore secundária" onClick={()=>commit({...page,locked:false,locks:{...page.locks,secondaryTree:!page.locks?.secondaryTree}})}>{page.locks?.secondaryTree?<Lock size={13}/>:<Unlock size={13}/>}</button></header><small className="rs-caption">Secundária · duas linhas distintas</small>{secondary?.slots.slice(1).map((row,i)=><div className="rs-row" key={i} role="group" aria-label={`Linha secundária ${i+1}`}>{row.runes.map(r=>runeButton(r,page.secondary))}</div>)}
 <div className="rs-shards"><h4>Fragmentos de atributos</h4>{SHARD_ROWS.map((row,slot)=><div className="rs-row" key={slot} role="group" aria-label={`Fragmento ${slot+1}`}>{row.map(value=>{const Icon=shardIcons[value as keyof typeof shardIcons]??Shield,selected=page.shards[slot]===value;const locked=page.locked||!!page.locks?.shards?.includes(slot);return <span className="rs-slot" key={value}><button type="button" className={`rs-icon rs-shard ${selected?'is-selected':''}`} style={{'--rune-color':'#c6b4ef'} as CSSProperties} aria-label={`${['Ofensivo','Flexível','Defensivo'][slot]}: ${SHARD_LABELS[value]}`} aria-pressed={selected} title={SHARD_LABELS[value]} onClick={()=>{if(!selected||!locked)commit(selectManualShard(page,slot,value));}}><Icon size={22}/></button>{selected&&<button type="button" className="rs-lock-toggle" aria-label={`${locked?'Destravar':'Travar'} fragmento ${slot+1}`} aria-pressed={locked} title={locked?'Clique para destravar e calcular automaticamente':'Clique para travar este fragmento'} onClick={()=>commit(selectManualShard(page,slot,value))}>{locked?<Lock size={13}/>:<Unlock size={13}/>}</button>}</span>;})}</div>)}</div></div></div>
 <p className="rs-caption">Escolha a runa pelo ícone. Clique no cadeado para travar ou liberar o slot.</p>{error&&<p className="notice error" role="alert">{error}</p>}</section>;
}
