'use client';
import {useState,type CSSProperties} from 'react';
import {Lock,Unlock} from 'lucide-react';
import type {Dataset,RunePage,Rune,Scenario} from './contracts';
import {calculateOptimalRunes} from './runeOptimizer';
import {runeCompatible} from './compatibility';
import {selectManualRune,switchRuneTree,selectManualShard} from './runeSelection';
import {ShardIcon} from './AttributeLabel';
import {SHARD_ROWS,SHARD_LABELS} from './shards';
import GuideText from './GuideText';
import {runeGuide,runeDraftAdvice} from './contextGuide';
import {plain} from './model';
export interface RuneSelectorProps {page:RunePage;data:Dataset;scenario:Scenario;onChange:(page:RunePage)=>void}
const colors:Record<number,string>={8000:'#deb65d',8100:'#e36a75',8200:'#88b8ef',8400:'#82c77b',8300:'#8fd9d8'};
const cdn='/assets/riot/icons/';

export default function RuneSelector({page,data,scenario,onChange}:RuneSelectorProps){
 const [error,setError]=useState(''),[highlight,setHighlight]=useState<number|null>(null);
 const primary=data.runes.find(t=>t.id===page.primary),secondary=data.runes.find(t=>t.id===page.secondary);
 function commit(next:RunePage){try{const resolved=calculateOptimalRunes({...scenario,player:{...scenario.player,runes:next}},data,scenario.weights,true);onChange(resolved);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}}
 function runeButton(r:Rune,tree:number,keystone=false){
  const selected=page.selected.includes(r.id),locked=page.locked||!!page.locks?.runes?.includes(r.id),compatibility=runeCompatible(r.id,scenario.player,data);
  return <span className="rs-slot" key={r.id}><button type="button" className={`rs-icon ${keystone?'rs-keystone':''} ${selected?'is-selected':''} ${highlight===r.id?'guide-highlight':''}`} data-rune-id={r.id} style={{'--rune-color':colors[tree]??'#b5c5dc'} as CSSProperties} disabled={!compatibility.allowed&&!selected} aria-label={`${r.name}${locked?' · escolha travada':''}`} aria-pressed={selected} title={`${r.name}\n${plain(r.longDesc||r.shortDesc)}${!compatibility.allowed?'\nIncompatível com o kit deste campeão.':''}`} onClick={()=>{if(!selected||!locked)commit(selectManualRune(page,data,r.id));}}>
   <img src={cdn+r.icon} alt=""/>
  </button>{selected&&<button type="button" className="rs-lock-toggle" aria-label={`${locked?'Destravar':'Travar'} ${r.name}`} aria-pressed={locked} title={locked?'Clique para destravar e calcular automaticamente':'Clique para travar esta runa'} onClick={()=>commit(selectManualRune(page,data,r.id))}>{locked?<Lock size={13}/>:<Unlock size={13}/>}</button>}</span>;
 }
 return <div className="educational-runes"><section className="rune-selector" aria-label="Seleção de runas"><div className="rs-toolbar"><span>Escolha suas runas</span></div>
 <div className="rs-tabs" role="group" aria-label="Árvore primária">{data.runes.map(t=><span className="rs-slot" key={t.id}><button type="button" className={t.id===page.primary?'is-selected':''} style={{'--rune-color':colors[t.id]} as CSSProperties} aria-label={`Árvore primária: ${t.name}`} aria-pressed={t.id===page.primary} title={t.name} onClick={()=>commit(switchRuneTree(page,data,t.id,'primary'))}><img src={cdn+t.icon} alt=""/></button>{t.id===page.primary&&<button type="button" className="rs-lock-toggle" aria-label="Alternar trava da árvore primária" aria-pressed={!!page.locks?.primaryTree} title="Travar ou destravar árvore primária" onClick={()=>commit({...page,locked:false,locks:{...page.locks,primaryTree:!page.locks?.primaryTree}})}>{page.locks?.primaryTree?<Lock size={13}/>:<Unlock size={13}/>}</button>}</span>)}</div>
 <div className="rs-columns"><div className="rs-primary" style={{'--rune-color':colors[page.primary]} as CSSProperties}><header><img src={primary?cdn+primary.icon:undefined} alt=""/><h4>{primary?.name}</h4><small>Primária</small></header>{primary?.slots.map((row,i)=><div className="rs-row" key={i} role="group" aria-label={i===0?'Runas essenciais':`Linha primária ${i}`}>{row.runes.map(r=>runeButton(r,page.primary,i===0))}</div>)}</div>
 <div className="rs-secondary" style={{'--rune-color':colors[page.secondary]} as CSSProperties}><header><img src={secondary?cdn+secondary.icon:undefined} alt=""/><label><span className="sr-only">Árvore secundária</span><select aria-label="Árvore secundária" value={page.secondary} onChange={e=>commit(switchRuneTree(page,data,Number(e.target.value),'secondary'))}>{data.runes.filter(t=>t.id!==page.primary).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button type="button" className="rs-tree-lock" aria-label="Alternar trava da árvore secundária" aria-pressed={!!page.locks?.secondaryTree} title="Travar ou destravar árvore secundária" onClick={()=>commit({...page,locked:false,locks:{...page.locks,secondaryTree:!page.locks?.secondaryTree}})}>{page.locks?.secondaryTree?<Lock size={13}/>:<Unlock size={13}/>}</button></header><small className="rs-caption">Secundária · duas linhas distintas</small>{secondary?.slots.slice(1).map((row,i)=><div className="rs-row" key={i} role="group" aria-label={`Linha secundária ${i+1}`}>{row.runes.map(r=>runeButton(r,page.secondary))}</div>)}
 <div className="rs-shards"><h4>Fragmentos de atributos</h4>{SHARD_ROWS.map((row,slot)=><div className="rs-row" key={slot} role="group" aria-label={`Fragmento ${slot+1}`}>{row.map(value=>{const selected=page.shards[slot]===value;const locked=page.locked||!!page.locks?.shards?.includes(slot);return <span className="rs-slot" key={value}><button type="button" className={`rs-icon rs-shard ${selected?'is-selected':''}`} style={{'--rune-color':'#c6b4ef'} as CSSProperties} aria-label={`${['Ofensivo','Flexível','Defensivo'][slot]}: ${SHARD_LABELS[value]}`} aria-pressed={selected} title={SHARD_LABELS[value]} onClick={()=>{if(!selected||!locked)commit(selectManualShard(page,slot,value));}}><ShardIcon shard={value} size={20}/></button>{selected&&<button type="button" className="rs-lock-toggle" aria-label={`${locked?'Destravar':'Travar'} fragmento ${slot+1}`} aria-pressed={locked} title={locked?'Clique para destravar e calcular automaticamente':'Clique para travar este fragmento'} onClick={()=>commit(selectManualShard(page,slot,value))}>{locked?<Lock size={13}/>:<Unlock size={13}/>}</button>}</span>;})}</div>)}</div></div></div><div className="selected-shards" aria-label="Fragmentos selecionados">{page.shards.map((shard,i)=><span key={i} title={['Ofensivo','Flexível','Defensivo'][i]}><ShardIcon shard={shard} size={18}/><span>{SHARD_LABELS[shard]??shard}</span></span>)}</div>
 <p className="rs-caption">Escolha a runa pelo ícone. Clique no cadeado para travar ou liberar o slot.</p>{error&&<p className="notice error" role="alert">{error}</p>}</section><details className="rune-lessons" aria-label="Por que usar estas runas"><summary>Entenda suas runas</summary><details className="rune-draft-advice"><summary>Plano de runas para este cenário</summary><p><GuideText text={runeDraftAdvice(scenario,data)} data={data}/></p><small className="hint">Orientação editorial por kit e função; não altera o cálculo nem presume win rate.</small></details><p className="hint">Estimativa de Kit · gatilhos do catálogo. Passe o mouse, toque ou use Tab nos cards para destacar a runa.</p>{data.runes.flatMap(t=>t.slots.flatMap(row=>row.runes)).filter(r=>page.selected.includes(r.id)).map(r=>{const g=runeGuide(r,scenario,data);return <article key={r.id} tabIndex={0} className={`guide-card ${highlight===r.id?'is-active':''}`} onMouseEnter={()=>setHighlight(r.id)} onMouseLeave={()=>setHighlight(null)} onFocus={()=>setHighlight(r.id)} onBlur={()=>setHighlight(null)} onClick={()=>setHighlight(r.id)} aria-label={`Explicação de ${r.name}`}><h4><img src={cdn+r.icon} alt=""/>{r.name}</h4><p className="rune-card-summary"><GuideText text={g.synergy} data={data}/></p><details className="rune-card-condition"><summary>Quando usar?</summary><p><GuideText text={g.condition} data={data}/></p></details><details><summary>Gatilho oficial e afinidade</summary><p>{g.description}</p><p className="hint">Score heurístico {g.score.score.toFixed(3)} · não representa dano medido nem taxa de vitória. Efeitos sem fórmula continuam fora do combate.</p></details></article>;})}</details></div>;
}
