'use client';
import {useEffect} from 'react';
import type {Dataset,Scenario} from './contracts';
import {ChampionSelect} from './components';
import ContextAssistant from './ContextAssistant';
import TeamComparison from './TeamComparison';
import {teamWorkspace,updateTeamWorkspace,editTeamSlot} from './teamWorkspace';
import {DRAFT_LANES} from './draft';
import {splashURL} from './skins';
const roles=['Topo','Selva','Meio','Atirador','Suporte'];
export default function TeamWorkspace({scenario:s,data,onChange}:{scenario:Scenario;data:Dataset;onChange:(s:Scenario)=>void}){const draft=teamWorkspace(s,data),signature=JSON.stringify(draft);useEffect(()=>{if(JSON.stringify(s.draft)!==signature||JSON.stringify(s.enemyTeam)!==JSON.stringify(draft.enemy))onChange(updateTeamWorkspace(s,draft));},[signature]);return <details className="panel team-workspace"><summary>Times, sinergias e counters</summary><p className="hint">Seu campeão, sua rota e seu adversário são os mesmos do laboratório. Complete os outros integrantes para analisar as equipes.</p><label className="field"><span>Sua rota</span><select aria-label="Sua rota na composição" value={s.player.lane} onChange={e=>onChange({...s,player:{...s.player,lane:e.target.value},counterPreset:undefined})}>{DRAFT_LANES.map((lane,i)=><option key={lane} value={lane}>{roles[i]}</option>)}</select></label><div className="results-grid">{(['own','enemy'] as const).map(side=><div key={side}><h3>{side==='own'?'Seu time':'Time inimigo'}</h3>{draft[side].map((id,i)=><div key={i} className={`team-champion-row ${side==='own'&&draft.active===i?'active-team-champion':''}`}>{id?<img className="team-champion-splash" src={splashURL(id)} alt={`Splash de ${data.champions[id].name}`} loading="lazy"/>:<span className="team-champion-empty">?</span>}<div className="team-champion-name">{id&&<strong>{data.champions[id].name}</strong>}{i===draft.active&&<small>{side==='own'?'Você · sincronizado com o laboratório':'Adversário direto · sincronizado'}</small>}<ChampionSelect empty={side==='enemy'||i!==draft.active} data={data} value={id} label={`${side==='own'?'Aliado':'Inimigo'} ${roles[i]}`} onChange={id=>onChange(editTeamSlot(s,data,side,i,id))}/></div></div>)}</div>)}</div><TeamComparison scenario={s} data={data} onChange={onChange} composition={draft}/><details><summary>Recomendações de counter</summary><ContextAssistant scenario={s} data={data} onChange={onChange} composition={draft}/></details></details>;}
