'use client';
import type {Dataset,Scenario,DraftState} from './contracts';
import {ChampionSelect} from './components';
import {analyzeTeam} from './teamAnalysis';
import {splashURL} from './skins';
export default function TeamComparison({scenario:s,data,onChange,composition}:{composition?:DraftState;scenario:Scenario;data:Dataset;onChange:(s:Scenario)=>void}){
 const own=composition?.own??[s.player.champion,...Array.from({length:4},(_,i)=>s.allies[i]??'')];
 const enemy=composition?.enemy??Array.from({length:5},(_,i)=>s.enemyTeam?.[i]??(i===0&&!s.matchupUnknown?s.enemy.champion:''));
 const a=analyzeTeam(own,data),b=analyzeTeam(enemy,data);
 const rows:[string,keyof Pick<typeof a,'selected'|'healing'|'shields'|'cc'|'tanks'|'burst'|'physical'|'magic'|'mixed'>][]=[['Campeões selecionados','selected'],['Com cura (própria ou aliada)','healing'],['Com escudo (próprio ou aliado)','shields'],['Com CC duro','cc'],['Frontline / tanques','tanks'],['Perfil de burst','burst'],['Perfil físico','physical'],['Perfil mágico','magic'],['Perfil misto','mixed']];
 function select(side:'own'|'enemy',index:number,id:string){const team=[...(side==='own'?own:enemy)];if(id&&team.some((v,i)=>i!==index&&v===id))return;team[index]=id;onChange(side==='own'?{...s,allies:team.slice(1)}:{...s,enemyTeam:team});}
 return <div className="team-comparison">{!composition&&<h3>Sinergias e comparação dos times</h3>}{!composition&&<><div className="results-grid">{(['own','enemy'] as const).map(side=><div key={side}><h3>{side==='own'?'Seu time':'Time inimigo'}</h3>{(side==='own'?own:enemy).map((id,i)=><div className="team-champion-row" key={i}>{id?<img className="team-champion-splash" src={splashURL(id)} alt={`Splash de ${data.champions[id].name}`} loading="lazy"/>:<span className="team-champion-empty" aria-hidden="true">?</span>}<div className="team-champion-name">{id&&<strong>{data.champions[id].name}</strong>}{side==='own'&&i===0?<small>Seu campeão</small>:<ChampionSelect empty data={data} value={id} label={`${side==='own'?'Aliado':'Inimigo'} ${side==='own'?i:i+1}`} onChange={id=>select(side,i,id)}/>}</div></div>)}</div>)}</div></>}<p className="hint">Preencha somente os campeões conhecidos. O combate usa seu adversário direto.</p><label className="slider-field"><span>Foco da build: lane {100-(s.teamPriority??0)}% · time inimigo {s.teamPriority??0}%</span><input aria-label="Prioridade do time inimigo" type="range" min="0" max="100" value={s.teamPriority??0} onChange={e=>onChange({...s,teamPriority:Number(e.target.value)})}/></label><p className="hint">Afeta os scores da build: DPS médio contra os alvos selecionados, EHP ponderado pela mitigação e respostas de kit. Slots vazios são omitidos. Outros inimigos usam atributos base no nível do adversário da lane, sem builds presumidas. Não é uma simulação 5 × 5; o botão de combate mantém o duelo.</p><details><summary>Capacidades e sinergias dos times</summary><table><thead><tr><th>Capacidade do kit</th><th>Seu time</th><th>Inimigos</th></tr></thead><tbody>{rows.map(([label,key])=><tr key={key}><td>{label}</td><td>{a[key]}</td><td>{b[key]}</td></tr>)}</tbody></table><div className="results-grid">{[a,b].map((team,i)=><div key={i}><h3>{i===0?'Sinergias do seu time':'Sinergias inimigas'}</h3>{team.synergies.map(text=><p key={text}>{text}</p>)}</div>)}</div><p>{a.selected!==b.selected?'Complete os dois times para comparar a cobertura de funções.':`Diferença de cobertura (seu time − inimigos): cura ${a.healing-b.healing}, escudos ${a.shields-b.shields}, CC duro ${a.cc-b.cc}, frontline ${a.tanks-b.tanks}. Mais fontes não garante vitória.`}</p><p className="hint">Contagens por características de kit, com cobertura parcial. Não são volumes de cura, duração de CC, percentuais de dano ou simulação 5 × 5. Valores de cura útil e CC em segundos aparecem no duelo quando as ações são configuradas; builds, alvos e execução mudam esses valores.</p></details></div>;
}
