'use client';
import {useEffect} from 'react';
import type {Dataset,Scenario} from './contracts';
import {ChampionSelect} from './components';
import ContextAssistant from './ContextAssistant';
import TeamComparison from './TeamComparison';
import {teamWorkspace,updateTeamWorkspace} from './teamWorkspace';
import {splashURL} from './skins';
const roles=['Topo','Selva','Meio','Atirador','Suporte'];
export default function TeamWorkspace({scenario:s,data,onChange}:{scenario:Scenario;data:Dataset;onChange:(s:Scenario)=>void}){const draft=teamWorkspace(s,data),signature=JSON.stringify(draft);useEffect(()=>{if(JSON.stringify(s.draft)!==signature||JSON.stringify(s.enemyTeam)!==JSON.stringify(draft.enemy))onChange(updateTeamWorkspace(s,draft));},[signature]);return <details className="panel team-workspace"><summary>Times, sinergias e counters</summary><p className="hint">Uma composição para análise e counters. Clique em um aliado para selecionar a prévia do draft; o campeão do laboratório só muda ao aplicar o counter.</p><div className="results-grid">{(['own','enemy'] as const).map(side=><div key={side}><h3>{side==='own'?'Seu time':'Time inimigo'}</h3>{draft[side].map((id,i)=><div key={i} className={`team-champion-row ${side==='own'&&draft.active===i?'active-team-champion':''}`}><button className="team-portrait-button" aria-label={`Prévia ${side==='own'?'aliada':'inimiga'} ${roles[i]}${id?`: ${data.champions[id].name}`:''}`} disabled={side==='enemy'||!id} aria-pressed={side==='own'&&draft.active===i} onClick={()=>onChange(updateTeamWorkspace(s,{...draft,active:i}))}>{id?<img className="team-champion-splash" src={splashURL(id)} alt={`Splash de ${data.champions[id].name}`} loading="lazy"/>:<span className="team-champion-empty">?</span>}</button><div className="team-champion-name">{id&&<strong>{data.champions[id].name}</strong>}<ChampionSelect empty data={data} value={id} label={`${side==='own'?'Aliado':'Inimigo'} ${roles[i]}`} onChange={id=>{if(id&&draft[side].some((old,n)=>n!==i&&old===id))return;onChange(updateTeamWorkspace(s,{...draft,[side]:draft[side].map((old,n)=>n===i?id:old)}));}}/></div></div>)}</div>)}</div><TeamComparison scenario={s} data={data} onChange={onChange} composition={draft}/><details><summary>Recomendações de counter</summary><ContextAssistant scenario={s} data={data} onChange={onChange} composition={draft}/></details></details>;}
